defmodule SchemaOrg.Accommodation do
  @moduledoc "An accommodation is a place that can accommodate human beings, e.g. a hotel room, a camping pitch, or a meeting room. Many accommodations are for overnight stays, but this is not a mandatory requirement.\nFor more specific types of accommodations not defined in schema.org, one can use `additionalType` with external vocabularies.\n\nSee also the [dedicated document on the use of schema.org for marking up hotels and other forms of accommodations](/docs/hotels.html)."

  defstruct [
    :accommodation_category,
    :accommodation_floor_plan,
    :additional_property,
    :additional_type,
    :address,
    :aggregate_rating,
    :alternate_name,
    :amenity_feature,
    :bed,
    :branch_code,
    :contained_in,
    :contained_in_place,
    :contains_place,
    :description,
    :disambiguating_description,
    :event,
    :events,
    :fax_number,
    :floor_level,
    :floor_size,
    :geo,
    :geo_contains,
    :geo_covered_by,
    :geo_covers,
    :geo_crosses,
    :geo_disjoint,
    :geo_equals,
    :geo_intersects,
    :geo_overlaps,
    :geo_touches,
    :geo_within,
    :global_location_number,
    :has_certification,
    :has_drive_through_service,
    :has_gs1_digital_link,
    :has_map,
    :identifier,
    :image,
    :is_accessible_for_free,
    :isic_v4,
    :keywords,
    :latitude,
    :lease_length,
    :logo,
    :longitude,
    :main_entity_of_page,
    :map,
    :maps,
    :maximum_attendee_capacity,
    :name,
    :number_of_bathrooms_total,
    :number_of_bedrooms,
    :number_of_full_bathrooms,
    :number_of_partial_bathrooms,
    :number_of_rooms,
    :occupancy,
    :opening_hours_specification,
    :owner,
    :permitted_usage,
    :pets_allowed,
    :photo,
    :photos,
    :potential_action,
    :public_access,
    :review,
    :reviews,
    :same_as,
    :slogan,
    :smoking_allowed,
    :special_opening_hours_specification,
    :subject_of,
    :telephone,
    :tour_booking_page,
    :url,
    :year_built
  ]

  @json_keys %{
    accommodation_category: "accommodationCategory",
    accommodation_floor_plan: "accommodationFloorPlan",
    additional_property: "additionalProperty",
    additional_type: "additionalType",
    address: "address",
    aggregate_rating: "aggregateRating",
    alternate_name: "alternateName",
    amenity_feature: "amenityFeature",
    bed: "bed",
    branch_code: "branchCode",
    contained_in: "containedIn",
    contained_in_place: "containedInPlace",
    contains_place: "containsPlace",
    description: "description",
    disambiguating_description: "disambiguatingDescription",
    event: "event",
    events: "events",
    fax_number: "faxNumber",
    floor_level: "floorLevel",
    floor_size: "floorSize",
    geo: "geo",
    geo_contains: "geoContains",
    geo_covered_by: "geoCoveredBy",
    geo_covers: "geoCovers",
    geo_crosses: "geoCrosses",
    geo_disjoint: "geoDisjoint",
    geo_equals: "geoEquals",
    geo_intersects: "geoIntersects",
    geo_overlaps: "geoOverlaps",
    geo_touches: "geoTouches",
    geo_within: "geoWithin",
    global_location_number: "globalLocationNumber",
    has_certification: "hasCertification",
    has_drive_through_service: "hasDriveThroughService",
    has_gs1_digital_link: "hasGS1DigitalLink",
    has_map: "hasMap",
    identifier: "identifier",
    image: "image",
    is_accessible_for_free: "isAccessibleForFree",
    isic_v4: "isicV4",
    keywords: "keywords",
    latitude: "latitude",
    lease_length: "leaseLength",
    logo: "logo",
    longitude: "longitude",
    main_entity_of_page: "mainEntityOfPage",
    map: "map",
    maps: "maps",
    maximum_attendee_capacity: "maximumAttendeeCapacity",
    name: "name",
    number_of_bathrooms_total: "numberOfBathroomsTotal",
    number_of_bedrooms: "numberOfBedrooms",
    number_of_full_bathrooms: "numberOfFullBathrooms",
    number_of_partial_bathrooms: "numberOfPartialBathrooms",
    number_of_rooms: "numberOfRooms",
    occupancy: "occupancy",
    opening_hours_specification: "openingHoursSpecification",
    owner: "owner",
    permitted_usage: "permittedUsage",
    pets_allowed: "petsAllowed",
    photo: "photo",
    photos: "photos",
    potential_action: "potentialAction",
    public_access: "publicAccess",
    review: "review",
    reviews: "reviews",
    same_as: "sameAs",
    slogan: "slogan",
    smoking_allowed: "smokingAllowed",
    special_opening_hours_specification: "specialOpeningHoursSpecification",
    subject_of: "subjectOf",
    telephone: "telephone",
    tour_booking_page: "tourBookingPage",
    url: "url",
    year_built: "yearBuilt"
  }

  @doc false
  def __schema_org__, do: %{type: "Accommodation", json_keys: @json_keys}

  @doc "Builds an empty `SchemaOrg.Accommodation` struct."
  def new, do: %__MODULE__{}
end
