defmodule SchemaOrg.AggregateOffer do
  @moduledoc "When a single product is associated with multiple offers (for example, the same pair of shoes is offered by different merchants), then AggregateOffer can be used.\\n\\nNote: AggregateOffers are normally expected to associate multiple offers that all share the same defined `businessFunction` value, or default to http://purl.org/goodrelations/v1#Sell if businessFunction is not explicitly defined."

  defstruct [
    :accepted_payment_method,
    :add_on,
    :additional_property,
    :additional_type,
    :advance_booking_requirement,
    :aggregate_rating,
    :alternate_name,
    :area_served,
    :asin,
    :availability,
    :availability_ends,
    :availability_starts,
    :available_at_or_from,
    :available_delivery_method,
    :business_function,
    :category,
    :checkout_page_url_template,
    :delivery_lead_time,
    :description,
    :disambiguating_description,
    :eligible_customer_type,
    :eligible_duration,
    :eligible_quantity,
    :eligible_region,
    :eligible_transaction_volume,
    :gtin,
    :gtin12,
    :gtin13,
    :gtin14,
    :gtin8,
    :has_adult_consideration,
    :has_gs1_digital_link,
    :has_measurement,
    :has_merchant_return_policy,
    :high_price,
    :identifier,
    :image,
    :includes_object,
    :ineligible_region,
    :inventory_level,
    :is_family_friendly,
    :item_condition,
    :item_offered,
    :lease_length,
    :low_price,
    :main_entity_of_page,
    :mobile_url,
    :mpn,
    :name,
    :offer_count,
    :offered_by,
    :offers,
    :owner,
    :potential_action,
    :price,
    :price_currency,
    :price_specification,
    :price_valid_until,
    :review,
    :reviews,
    :same_as,
    :seller,
    :serial_number,
    :shipping_details,
    :sku,
    :subject_of,
    :url,
    :valid_for_member_tier,
    :valid_from,
    :valid_through,
    :warranty
  ]

  @json_keys %{
    accepted_payment_method: "acceptedPaymentMethod",
    add_on: "addOn",
    additional_property: "additionalProperty",
    additional_type: "additionalType",
    advance_booking_requirement: "advanceBookingRequirement",
    aggregate_rating: "aggregateRating",
    alternate_name: "alternateName",
    area_served: "areaServed",
    asin: "asin",
    availability: "availability",
    availability_ends: "availabilityEnds",
    availability_starts: "availabilityStarts",
    available_at_or_from: "availableAtOrFrom",
    available_delivery_method: "availableDeliveryMethod",
    business_function: "businessFunction",
    category: "category",
    checkout_page_url_template: "checkoutPageURLTemplate",
    delivery_lead_time: "deliveryLeadTime",
    description: "description",
    disambiguating_description: "disambiguatingDescription",
    eligible_customer_type: "eligibleCustomerType",
    eligible_duration: "eligibleDuration",
    eligible_quantity: "eligibleQuantity",
    eligible_region: "eligibleRegion",
    eligible_transaction_volume: "eligibleTransactionVolume",
    gtin: "gtin",
    gtin12: "gtin12",
    gtin13: "gtin13",
    gtin14: "gtin14",
    gtin8: "gtin8",
    has_adult_consideration: "hasAdultConsideration",
    has_gs1_digital_link: "hasGS1DigitalLink",
    has_measurement: "hasMeasurement",
    has_merchant_return_policy: "hasMerchantReturnPolicy",
    high_price: "highPrice",
    identifier: "identifier",
    image: "image",
    includes_object: "includesObject",
    ineligible_region: "ineligibleRegion",
    inventory_level: "inventoryLevel",
    is_family_friendly: "isFamilyFriendly",
    item_condition: "itemCondition",
    item_offered: "itemOffered",
    lease_length: "leaseLength",
    low_price: "lowPrice",
    main_entity_of_page: "mainEntityOfPage",
    mobile_url: "mobileUrl",
    mpn: "mpn",
    name: "name",
    offer_count: "offerCount",
    offered_by: "offeredBy",
    offers: "offers",
    owner: "owner",
    potential_action: "potentialAction",
    price: "price",
    price_currency: "priceCurrency",
    price_specification: "priceSpecification",
    price_valid_until: "priceValidUntil",
    review: "review",
    reviews: "reviews",
    same_as: "sameAs",
    seller: "seller",
    serial_number: "serialNumber",
    shipping_details: "shippingDetails",
    sku: "sku",
    subject_of: "subjectOf",
    url: "url",
    valid_for_member_tier: "validForMemberTier",
    valid_from: "validFrom",
    valid_through: "validThrough",
    warranty: "warranty"
  }

  @doc false
  def __schema_org__, do: %{type: "AggregateOffer", json_keys: @json_keys}

  @doc "Builds an empty `SchemaOrg.AggregateOffer` struct."
  def new, do: %__MODULE__{}
end
