defmodule SchemaOrg.BarOrPub do
  @moduledoc "A bar or pub."

  defstruct [
    :accepted_payment_method,
    :accepts_reservations,
    :actionable_feedback_policy,
    :additional_property,
    :additional_type,
    :address,
    :agent_interaction_statistic,
    :aggregate_rating,
    :alternate_name,
    :alumni,
    :amenity_feature,
    :area_served,
    :award,
    :awards,
    :branch_code,
    :branch_of,
    :brand,
    :company_registration,
    :contact_point,
    :contact_points,
    :contained_in,
    :contained_in_place,
    :contains_place,
    :corrections_policy,
    :currencies_accepted,
    :department,
    :description,
    :disambiguating_description,
    :dissolution_date,
    :diversity_policy,
    :diversity_staffing_report,
    :duns,
    :email,
    :employee,
    :employees,
    :ethics_policy,
    :event,
    :events,
    :fax_number,
    :floor_level,
    :founder,
    :founders,
    :founding_date,
    :founding_location,
    :funder,
    :funding,
    :geo,
    :geo_contains,
    :geo_covered_by,
    :geo_covers,
    :geo_crosses,
    :geo_disjoint,
    :geo_equals,
    :geo_intersects,
    :geo_overlaps,
    :geo_touches,
    :geo_within,
    :global_location_number,
    :has_certification,
    :has_credential,
    :has_drive_through_service,
    :has_gs1_digital_link,
    :has_map,
    :has_member_program,
    :has_menu,
    :has_merchant_return_policy,
    :has_offer_catalog,
    :has_pos,
    :has_shipping_service,
    :identifier,
    :image,
    :interaction_statistic,
    :is_accessible_for_free,
    :isic_v4,
    :iso6523_code,
    :keywords,
    :knows_about,
    :knows_language,
    :latitude,
    :legal_address,
    :legal_name,
    :legal_representative,
    :lei_code,
    :location,
    :logo,
    :longitude,
    :main_entity_of_page,
    :makes_offer,
    :map,
    :maps,
    :maximum_attendee_capacity,
    :member,
    :member_of,
    :members,
    :menu,
    :naics,
    :name,
    :nonprofit_status,
    :number_of_employees,
    :opening_hours,
    :opening_hours_specification,
    :owner,
    :ownership_funding_info,
    :owns,
    :parent_organization,
    :payment_accepted,
    :photo,
    :photos,
    :potential_action,
    :price_range,
    :public_access,
    :publishing_principles,
    :review,
    :reviews,
    :same_as,
    :seeks,
    :serves_cuisine,
    :service_area,
    :skills,
    :slogan,
    :smoking_allowed,
    :special_opening_hours_specification,
    :sponsor,
    :star_rating,
    :sub_organization,
    :subject_of,
    :tax_id,
    :telephone,
    :tour_booking_page,
    :unnamed_sources_policy,
    :url,
    :vat_id
  ]

  @json_keys %{
    accepted_payment_method: "acceptedPaymentMethod",
    accepts_reservations: "acceptsReservations",
    actionable_feedback_policy: "actionableFeedbackPolicy",
    additional_property: "additionalProperty",
    additional_type: "additionalType",
    address: "address",
    agent_interaction_statistic: "agentInteractionStatistic",
    aggregate_rating: "aggregateRating",
    alternate_name: "alternateName",
    alumni: "alumni",
    amenity_feature: "amenityFeature",
    area_served: "areaServed",
    award: "award",
    awards: "awards",
    branch_code: "branchCode",
    branch_of: "branchOf",
    brand: "brand",
    company_registration: "companyRegistration",
    contact_point: "contactPoint",
    contact_points: "contactPoints",
    contained_in: "containedIn",
    contained_in_place: "containedInPlace",
    contains_place: "containsPlace",
    corrections_policy: "correctionsPolicy",
    currencies_accepted: "currenciesAccepted",
    department: "department",
    description: "description",
    disambiguating_description: "disambiguatingDescription",
    dissolution_date: "dissolutionDate",
    diversity_policy: "diversityPolicy",
    diversity_staffing_report: "diversityStaffingReport",
    duns: "duns",
    email: "email",
    employee: "employee",
    employees: "employees",
    ethics_policy: "ethicsPolicy",
    event: "event",
    events: "events",
    fax_number: "faxNumber",
    floor_level: "floorLevel",
    founder: "founder",
    founders: "founders",
    founding_date: "foundingDate",
    founding_location: "foundingLocation",
    funder: "funder",
    funding: "funding",
    geo: "geo",
    geo_contains: "geoContains",
    geo_covered_by: "geoCoveredBy",
    geo_covers: "geoCovers",
    geo_crosses: "geoCrosses",
    geo_disjoint: "geoDisjoint",
    geo_equals: "geoEquals",
    geo_intersects: "geoIntersects",
    geo_overlaps: "geoOverlaps",
    geo_touches: "geoTouches",
    geo_within: "geoWithin",
    global_location_number: "globalLocationNumber",
    has_certification: "hasCertification",
    has_credential: "hasCredential",
    has_drive_through_service: "hasDriveThroughService",
    has_gs1_digital_link: "hasGS1DigitalLink",
    has_map: "hasMap",
    has_member_program: "hasMemberProgram",
    has_menu: "hasMenu",
    has_merchant_return_policy: "hasMerchantReturnPolicy",
    has_offer_catalog: "hasOfferCatalog",
    has_pos: "hasPOS",
    has_shipping_service: "hasShippingService",
    identifier: "identifier",
    image: "image",
    interaction_statistic: "interactionStatistic",
    is_accessible_for_free: "isAccessibleForFree",
    isic_v4: "isicV4",
    iso6523_code: "iso6523Code",
    keywords: "keywords",
    knows_about: "knowsAbout",
    knows_language: "knowsLanguage",
    latitude: "latitude",
    legal_address: "legalAddress",
    legal_name: "legalName",
    legal_representative: "legalRepresentative",
    lei_code: "leiCode",
    location: "location",
    logo: "logo",
    longitude: "longitude",
    main_entity_of_page: "mainEntityOfPage",
    makes_offer: "makesOffer",
    map: "map",
    maps: "maps",
    maximum_attendee_capacity: "maximumAttendeeCapacity",
    member: "member",
    member_of: "memberOf",
    members: "members",
    menu: "menu",
    naics: "naics",
    name: "name",
    nonprofit_status: "nonprofitStatus",
    number_of_employees: "numberOfEmployees",
    opening_hours: "openingHours",
    opening_hours_specification: "openingHoursSpecification",
    owner: "owner",
    ownership_funding_info: "ownershipFundingInfo",
    owns: "owns",
    parent_organization: "parentOrganization",
    payment_accepted: "paymentAccepted",
    photo: "photo",
    photos: "photos",
    potential_action: "potentialAction",
    price_range: "priceRange",
    public_access: "publicAccess",
    publishing_principles: "publishingPrinciples",
    review: "review",
    reviews: "reviews",
    same_as: "sameAs",
    seeks: "seeks",
    serves_cuisine: "servesCuisine",
    service_area: "serviceArea",
    skills: "skills",
    slogan: "slogan",
    smoking_allowed: "smokingAllowed",
    special_opening_hours_specification: "specialOpeningHoursSpecification",
    sponsor: "sponsor",
    star_rating: "starRating",
    sub_organization: "subOrganization",
    subject_of: "subjectOf",
    tax_id: "taxID",
    telephone: "telephone",
    tour_booking_page: "tourBookingPage",
    unnamed_sources_policy: "unnamedSourcesPolicy",
    url: "url",
    vat_id: "vatID"
  }

  @doc false
  def __schema_org__, do: %{type: "BarOrPub", json_keys: @json_keys}

  @doc "Builds an empty `SchemaOrg.BarOrPub` struct."
  def new, do: %__MODULE__{}
end
