defmodule SchemaOrg.BroadcastService do
  @moduledoc "A delivery service through which content is provided via broadcast over the air or online."

  defstruct [
    :additional_type,
    :aggregate_rating,
    :alternate_name,
    :area,
    :area_served,
    :audience,
    :available_channel,
    :award,
    :brand,
    :broadcast_affiliate_of,
    :broadcast_display_name,
    :broadcast_frequency,
    :broadcast_timezone,
    :broadcaster,
    :broker,
    :call_sign,
    :category,
    :description,
    :disambiguating_description,
    :has_broadcast_channel,
    :has_certification,
    :has_offer_catalog,
    :hours_available,
    :identifier,
    :image,
    :in_language,
    :is_related_to,
    :is_similar_to,
    :logo,
    :main_entity_of_page,
    :name,
    :offers,
    :owner,
    :parent_service,
    :potential_action,
    :produces,
    :provider,
    :provider_mobility,
    :review,
    :same_as,
    :service_area,
    :service_audience,
    :service_output,
    :service_type,
    :slogan,
    :subject_of,
    :terms_of_service,
    :url,
    :video_format
  ]

  @json_keys %{
    additional_type: "additionalType",
    aggregate_rating: "aggregateRating",
    alternate_name: "alternateName",
    area: "area",
    area_served: "areaServed",
    audience: "audience",
    available_channel: "availableChannel",
    award: "award",
    brand: "brand",
    broadcast_affiliate_of: "broadcastAffiliateOf",
    broadcast_display_name: "broadcastDisplayName",
    broadcast_frequency: "broadcastFrequency",
    broadcast_timezone: "broadcastTimezone",
    broadcaster: "broadcaster",
    broker: "broker",
    call_sign: "callSign",
    category: "category",
    description: "description",
    disambiguating_description: "disambiguatingDescription",
    has_broadcast_channel: "hasBroadcastChannel",
    has_certification: "hasCertification",
    has_offer_catalog: "hasOfferCatalog",
    hours_available: "hoursAvailable",
    identifier: "identifier",
    image: "image",
    in_language: "inLanguage",
    is_related_to: "isRelatedTo",
    is_similar_to: "isSimilarTo",
    logo: "logo",
    main_entity_of_page: "mainEntityOfPage",
    name: "name",
    offers: "offers",
    owner: "owner",
    parent_service: "parentService",
    potential_action: "potentialAction",
    produces: "produces",
    provider: "provider",
    provider_mobility: "providerMobility",
    review: "review",
    same_as: "sameAs",
    service_area: "serviceArea",
    service_audience: "serviceAudience",
    service_output: "serviceOutput",
    service_type: "serviceType",
    slogan: "slogan",
    subject_of: "subjectOf",
    terms_of_service: "termsOfService",
    url: "url",
    video_format: "videoFormat"
  }

  @doc false
  def __schema_org__, do: %{type: "BroadcastService", json_keys: @json_keys}

  @doc "Builds an empty `SchemaOrg.BroadcastService` struct."
  def new, do: %__MODULE__{}
end
