defmodule SchemaOrg.BusOrCoach do
  @moduledoc "A bus (also omnibus or autobus) is a road vehicle designed to carry passengers. Coaches are luxury buses, usually in service for long distance travel."

  defstruct [
    :acceleration_time,
    :acriss_code,
    :additional_property,
    :additional_type,
    :aggregate_rating,
    :alternate_name,
    :asin,
    :audience,
    :award,
    :awards,
    :body_type,
    :brand,
    :call_sign,
    :cargo_volume,
    :category,
    :color,
    :color_swatch,
    :country_of_assembly,
    :country_of_last_processing,
    :country_of_origin,
    :date_vehicle_first_registered,
    :depth,
    :description,
    :disambiguating_description,
    :display_location,
    :drive_wheel_configuration,
    :emissions_co2,
    :fuel_capacity,
    :fuel_consumption,
    :fuel_efficiency,
    :fuel_type,
    :funding,
    :gtin,
    :gtin12,
    :gtin13,
    :gtin14,
    :gtin8,
    :has_adult_consideration,
    :has_certification,
    :has_energy_consumption_details,
    :has_gs1_digital_link,
    :has_measurement,
    :has_merchant_return_policy,
    :height,
    :identifier,
    :image,
    :in_product_group_with_id,
    :is_accessory_or_spare_part_for,
    :is_consumable_for,
    :is_family_friendly,
    :is_related_to,
    :is_similar_to,
    :is_variant_of,
    :item_condition,
    :keywords,
    :known_vehicle_damages,
    :logo,
    :main_entity_of_page,
    :manufacturer,
    :material,
    :meets_emission_standard,
    :mileage_from_odometer,
    :mobile_url,
    :model,
    :model_date,
    :mpn,
    :name,
    :negative_notes,
    :nsn,
    :number_of_airbags,
    :number_of_axles,
    :number_of_doors,
    :number_of_forward_gears,
    :number_of_previous_owners,
    :offers,
    :owner,
    :pattern,
    :payload,
    :positive_notes,
    :potential_action,
    :product_id,
    :production_date,
    :purchase_date,
    :release_date,
    :review,
    :reviews,
    :roof_load,
    :same_as,
    :seating_capacity,
    :size,
    :sku,
    :slogan,
    :speed,
    :steering_position,
    :subject_of,
    :tongue_weight,
    :trailer_weight,
    :url,
    :vehicle_configuration,
    :vehicle_engine,
    :vehicle_identification_number,
    :vehicle_interior_color,
    :vehicle_interior_type,
    :vehicle_model_date,
    :vehicle_seating_capacity,
    :vehicle_special_usage,
    :vehicle_transmission,
    :weight,
    :weight_total,
    :wheelbase,
    :width
  ]

  @json_keys %{
    acceleration_time: "accelerationTime",
    acriss_code: "acrissCode",
    additional_property: "additionalProperty",
    additional_type: "additionalType",
    aggregate_rating: "aggregateRating",
    alternate_name: "alternateName",
    asin: "asin",
    audience: "audience",
    award: "award",
    awards: "awards",
    body_type: "bodyType",
    brand: "brand",
    call_sign: "callSign",
    cargo_volume: "cargoVolume",
    category: "category",
    color: "color",
    color_swatch: "colorSwatch",
    country_of_assembly: "countryOfAssembly",
    country_of_last_processing: "countryOfLastProcessing",
    country_of_origin: "countryOfOrigin",
    date_vehicle_first_registered: "dateVehicleFirstRegistered",
    depth: "depth",
    description: "description",
    disambiguating_description: "disambiguatingDescription",
    display_location: "displayLocation",
    drive_wheel_configuration: "driveWheelConfiguration",
    emissions_co2: "emissionsCO2",
    fuel_capacity: "fuelCapacity",
    fuel_consumption: "fuelConsumption",
    fuel_efficiency: "fuelEfficiency",
    fuel_type: "fuelType",
    funding: "funding",
    gtin: "gtin",
    gtin12: "gtin12",
    gtin13: "gtin13",
    gtin14: "gtin14",
    gtin8: "gtin8",
    has_adult_consideration: "hasAdultConsideration",
    has_certification: "hasCertification",
    has_energy_consumption_details: "hasEnergyConsumptionDetails",
    has_gs1_digital_link: "hasGS1DigitalLink",
    has_measurement: "hasMeasurement",
    has_merchant_return_policy: "hasMerchantReturnPolicy",
    height: "height",
    identifier: "identifier",
    image: "image",
    in_product_group_with_id: "inProductGroupWithID",
    is_accessory_or_spare_part_for: "isAccessoryOrSparePartFor",
    is_consumable_for: "isConsumableFor",
    is_family_friendly: "isFamilyFriendly",
    is_related_to: "isRelatedTo",
    is_similar_to: "isSimilarTo",
    is_variant_of: "isVariantOf",
    item_condition: "itemCondition",
    keywords: "keywords",
    known_vehicle_damages: "knownVehicleDamages",
    logo: "logo",
    main_entity_of_page: "mainEntityOfPage",
    manufacturer: "manufacturer",
    material: "material",
    meets_emission_standard: "meetsEmissionStandard",
    mileage_from_odometer: "mileageFromOdometer",
    mobile_url: "mobileUrl",
    model: "model",
    model_date: "modelDate",
    mpn: "mpn",
    name: "name",
    negative_notes: "negativeNotes",
    nsn: "nsn",
    number_of_airbags: "numberOfAirbags",
    number_of_axles: "numberOfAxles",
    number_of_doors: "numberOfDoors",
    number_of_forward_gears: "numberOfForwardGears",
    number_of_previous_owners: "numberOfPreviousOwners",
    offers: "offers",
    owner: "owner",
    pattern: "pattern",
    payload: "payload",
    positive_notes: "positiveNotes",
    potential_action: "potentialAction",
    product_id: "productID",
    production_date: "productionDate",
    purchase_date: "purchaseDate",
    release_date: "releaseDate",
    review: "review",
    reviews: "reviews",
    roof_load: "roofLoad",
    same_as: "sameAs",
    seating_capacity: "seatingCapacity",
    size: "size",
    sku: "sku",
    slogan: "slogan",
    speed: "speed",
    steering_position: "steeringPosition",
    subject_of: "subjectOf",
    tongue_weight: "tongueWeight",
    trailer_weight: "trailerWeight",
    url: "url",
    vehicle_configuration: "vehicleConfiguration",
    vehicle_engine: "vehicleEngine",
    vehicle_identification_number: "vehicleIdentificationNumber",
    vehicle_interior_color: "vehicleInteriorColor",
    vehicle_interior_type: "vehicleInteriorType",
    vehicle_model_date: "vehicleModelDate",
    vehicle_seating_capacity: "vehicleSeatingCapacity",
    vehicle_special_usage: "vehicleSpecialUsage",
    vehicle_transmission: "vehicleTransmission",
    weight: "weight",
    weight_total: "weightTotal",
    wheelbase: "wheelbase",
    width: "width"
  }

  @doc false
  def __schema_org__, do: %{type: "BusOrCoach", json_keys: @json_keys}

  @doc "Builds an empty `SchemaOrg.BusOrCoach` struct."
  def new, do: %__MODULE__{}
end
