defmodule SchemaOrg.CatholicChurch do
  @moduledoc "A Catholic church."

  defstruct [
    :additional_property,
    :additional_type,
    :address,
    :aggregate_rating,
    :alternate_name,
    :amenity_feature,
    :branch_code,
    :contained_in,
    :contained_in_place,
    :contains_place,
    :description,
    :disambiguating_description,
    :event,
    :events,
    :fax_number,
    :geo,
    :geo_contains,
    :geo_covered_by,
    :geo_covers,
    :geo_crosses,
    :geo_disjoint,
    :geo_equals,
    :geo_intersects,
    :geo_overlaps,
    :geo_touches,
    :geo_within,
    :global_location_number,
    :has_certification,
    :has_drive_through_service,
    :has_gs1_digital_link,
    :has_map,
    :identifier,
    :image,
    :is_accessible_for_free,
    :isic_v4,
    :keywords,
    :latitude,
    :logo,
    :longitude,
    :main_entity_of_page,
    :map,
    :maps,
    :maximum_attendee_capacity,
    :name,
    :opening_hours,
    :opening_hours_specification,
    :owner,
    :photo,
    :photos,
    :potential_action,
    :public_access,
    :review,
    :reviews,
    :same_as,
    :slogan,
    :smoking_allowed,
    :special_opening_hours_specification,
    :subject_of,
    :telephone,
    :tour_booking_page,
    :url
  ]

  @json_keys %{
    additional_property: "additionalProperty",
    additional_type: "additionalType",
    address: "address",
    aggregate_rating: "aggregateRating",
    alternate_name: "alternateName",
    amenity_feature: "amenityFeature",
    branch_code: "branchCode",
    contained_in: "containedIn",
    contained_in_place: "containedInPlace",
    contains_place: "containsPlace",
    description: "description",
    disambiguating_description: "disambiguatingDescription",
    event: "event",
    events: "events",
    fax_number: "faxNumber",
    geo: "geo",
    geo_contains: "geoContains",
    geo_covered_by: "geoCoveredBy",
    geo_covers: "geoCovers",
    geo_crosses: "geoCrosses",
    geo_disjoint: "geoDisjoint",
    geo_equals: "geoEquals",
    geo_intersects: "geoIntersects",
    geo_overlaps: "geoOverlaps",
    geo_touches: "geoTouches",
    geo_within: "geoWithin",
    global_location_number: "globalLocationNumber",
    has_certification: "hasCertification",
    has_drive_through_service: "hasDriveThroughService",
    has_gs1_digital_link: "hasGS1DigitalLink",
    has_map: "hasMap",
    identifier: "identifier",
    image: "image",
    is_accessible_for_free: "isAccessibleForFree",
    isic_v4: "isicV4",
    keywords: "keywords",
    latitude: "latitude",
    logo: "logo",
    longitude: "longitude",
    main_entity_of_page: "mainEntityOfPage",
    map: "map",
    maps: "maps",
    maximum_attendee_capacity: "maximumAttendeeCapacity",
    name: "name",
    opening_hours: "openingHours",
    opening_hours_specification: "openingHoursSpecification",
    owner: "owner",
    photo: "photo",
    photos: "photos",
    potential_action: "potentialAction",
    public_access: "publicAccess",
    review: "review",
    reviews: "reviews",
    same_as: "sameAs",
    slogan: "slogan",
    smoking_allowed: "smokingAllowed",
    special_opening_hours_specification: "specialOpeningHoursSpecification",
    subject_of: "subjectOf",
    telephone: "telephone",
    tour_booking_page: "tourBookingPage",
    url: "url"
  }

  @doc false
  def __schema_org__, do: %{type: "CatholicChurch", json_keys: @json_keys}

  @doc "Builds an empty `SchemaOrg.CatholicChurch` struct."
  def new, do: %__MODULE__{}
end
