defmodule SchemaOrg.CourseInstance do
  @moduledoc "An instance of a `Course` which is distinct from other instances because it is offered at a different time or location or through different media or modes of study or to a specific section of students."

  defstruct [
    :about,
    :actor,
    :additional_type,
    :aggregate_rating,
    :alternate_name,
    :attendee,
    :attendees,
    :audience,
    :composer,
    :contributor,
    :course_mode,
    :course_schedule,
    :course_workload,
    :description,
    :director,
    :disambiguating_description,
    :door_time,
    :duration,
    :end_date,
    :event_attendance_mode,
    :event_schedule,
    :event_status,
    :funder,
    :funding,
    :has_participation_offer,
    :has_sponsorship_offer,
    :identifier,
    :image,
    :in_language,
    :instructor,
    :is_accessible_for_free,
    :keywords,
    :location,
    :main_entity_of_page,
    :maximum_attendee_capacity,
    :maximum_physical_attendee_capacity,
    :maximum_virtual_attendee_capacity,
    :name,
    :offers,
    :organizer,
    :owner,
    :performer,
    :performers,
    :potential_action,
    :previous_start_date,
    :recorded_in,
    :remaining_attendee_capacity,
    :review,
    :same_as,
    :sponsor,
    :start_date,
    :sub_event,
    :sub_events,
    :subject_of,
    :super_event,
    :translator,
    :typical_age_range,
    :url,
    :work_featured,
    :work_performed
  ]

  @json_keys %{
    about: "about",
    actor: "actor",
    additional_type: "additionalType",
    aggregate_rating: "aggregateRating",
    alternate_name: "alternateName",
    attendee: "attendee",
    attendees: "attendees",
    audience: "audience",
    composer: "composer",
    contributor: "contributor",
    course_mode: "courseMode",
    course_schedule: "courseSchedule",
    course_workload: "courseWorkload",
    description: "description",
    director: "director",
    disambiguating_description: "disambiguatingDescription",
    door_time: "doorTime",
    duration: "duration",
    end_date: "endDate",
    event_attendance_mode: "eventAttendanceMode",
    event_schedule: "eventSchedule",
    event_status: "eventStatus",
    funder: "funder",
    funding: "funding",
    has_participation_offer: "hasParticipationOffer",
    has_sponsorship_offer: "hasSponsorshipOffer",
    identifier: "identifier",
    image: "image",
    in_language: "inLanguage",
    instructor: "instructor",
    is_accessible_for_free: "isAccessibleForFree",
    keywords: "keywords",
    location: "location",
    main_entity_of_page: "mainEntityOfPage",
    maximum_attendee_capacity: "maximumAttendeeCapacity",
    maximum_physical_attendee_capacity: "maximumPhysicalAttendeeCapacity",
    maximum_virtual_attendee_capacity: "maximumVirtualAttendeeCapacity",
    name: "name",
    offers: "offers",
    organizer: "organizer",
    owner: "owner",
    performer: "performer",
    performers: "performers",
    potential_action: "potentialAction",
    previous_start_date: "previousStartDate",
    recorded_in: "recordedIn",
    remaining_attendee_capacity: "remainingAttendeeCapacity",
    review: "review",
    same_as: "sameAs",
    sponsor: "sponsor",
    start_date: "startDate",
    sub_event: "subEvent",
    sub_events: "subEvents",
    subject_of: "subjectOf",
    super_event: "superEvent",
    translator: "translator",
    typical_age_range: "typicalAgeRange",
    url: "url",
    work_featured: "workFeatured",
    work_performed: "workPerformed"
  }

  @doc false
  def __schema_org__, do: %{type: "CourseInstance", json_keys: @json_keys}

  @doc "Builds an empty `SchemaOrg.CourseInstance` struct."
  def new, do: %__MODULE__{}
end
