defmodule SchemaOrg.CreditCard do
  @moduledoc "A card payment method of a particular brand or name.  Used to mark up a particular payment method and/or the financial product/service that supplies the card account.\\n\\nCommonly used values:\\n\\n* http://purl.org/goodrelations/v1#AmericanExpress\\n* http://purl.org/goodrelations/v1#DinersClub\\n* http://purl.org/goodrelations/v1#Discover\\n* http://purl.org/goodrelations/v1#JCB\\n* http://purl.org/goodrelations/v1#MasterCard\\n* http://purl.org/goodrelations/v1#VISA\n       "

  defstruct [
    :additional_type,
    :aggregate_rating,
    :alternate_name,
    :amount,
    :annual_percentage_rate,
    :area_served,
    :audience,
    :available_channel,
    :award,
    :brand,
    :broker,
    :cash_back,
    :category,
    :contactless_payment,
    :currency,
    :description,
    :disambiguating_description,
    :fees_and_commissions_specification,
    :floor_limit,
    :grace_period,
    :has_certification,
    :has_offer_catalog,
    :hours_available,
    :identifier,
    :image,
    :interest_rate,
    :is_related_to,
    :is_similar_to,
    :loan_repayment_form,
    :loan_term,
    :loan_type,
    :logo,
    :main_entity_of_page,
    :monthly_minimum_repayment_amount,
    :name,
    :offers,
    :owner,
    :payment_method_type,
    :potential_action,
    :produces,
    :provider,
    :provider_mobility,
    :recourse_loan,
    :renegotiable_loan,
    :required_collateral,
    :review,
    :same_as,
    :service_area,
    :service_audience,
    :service_output,
    :service_type,
    :slogan,
    :subject_of,
    :terms_of_service,
    :url
  ]

  @json_keys %{
    additional_type: "additionalType",
    aggregate_rating: "aggregateRating",
    alternate_name: "alternateName",
    amount: "amount",
    annual_percentage_rate: "annualPercentageRate",
    area_served: "areaServed",
    audience: "audience",
    available_channel: "availableChannel",
    award: "award",
    brand: "brand",
    broker: "broker",
    cash_back: "cashBack",
    category: "category",
    contactless_payment: "contactlessPayment",
    currency: "currency",
    description: "description",
    disambiguating_description: "disambiguatingDescription",
    fees_and_commissions_specification: "feesAndCommissionsSpecification",
    floor_limit: "floorLimit",
    grace_period: "gracePeriod",
    has_certification: "hasCertification",
    has_offer_catalog: "hasOfferCatalog",
    hours_available: "hoursAvailable",
    identifier: "identifier",
    image: "image",
    interest_rate: "interestRate",
    is_related_to: "isRelatedTo",
    is_similar_to: "isSimilarTo",
    loan_repayment_form: "loanRepaymentForm",
    loan_term: "loanTerm",
    loan_type: "loanType",
    logo: "logo",
    main_entity_of_page: "mainEntityOfPage",
    monthly_minimum_repayment_amount: "monthlyMinimumRepaymentAmount",
    name: "name",
    offers: "offers",
    owner: "owner",
    payment_method_type: "paymentMethodType",
    potential_action: "potentialAction",
    produces: "produces",
    provider: "provider",
    provider_mobility: "providerMobility",
    recourse_loan: "recourseLoan",
    renegotiable_loan: "renegotiableLoan",
    required_collateral: "requiredCollateral",
    review: "review",
    same_as: "sameAs",
    service_area: "serviceArea",
    service_audience: "serviceAudience",
    service_output: "serviceOutput",
    service_type: "serviceType",
    slogan: "slogan",
    subject_of: "subjectOf",
    terms_of_service: "termsOfService",
    url: "url"
  }

  @doc false
  def __schema_org__, do: %{type: "CreditCard", json_keys: @json_keys}

  @doc "Builds an empty `SchemaOrg.CreditCard` struct."
  def new, do: %__MODULE__{}
end
