defmodule SchemaOrg.Demand do
  @moduledoc "A demand entity represents the public, not necessarily binding, not necessarily exclusive, announcement by an organization or person to seek a certain type of goods or services. For describing demand using this type, the very same properties used for Offer apply."

  defstruct [
    :accepted_payment_method,
    :additional_type,
    :advance_booking_requirement,
    :alternate_name,
    :area_served,
    :asin,
    :availability,
    :availability_ends,
    :availability_starts,
    :available_at_or_from,
    :available_delivery_method,
    :business_function,
    :delivery_lead_time,
    :description,
    :disambiguating_description,
    :eligible_customer_type,
    :eligible_duration,
    :eligible_quantity,
    :eligible_region,
    :eligible_transaction_volume,
    :gtin,
    :gtin12,
    :gtin13,
    :gtin14,
    :gtin8,
    :identifier,
    :image,
    :includes_object,
    :ineligible_region,
    :inventory_level,
    :item_condition,
    :item_offered,
    :main_entity_of_page,
    :mpn,
    :name,
    :owner,
    :potential_action,
    :price_specification,
    :same_as,
    :seller,
    :serial_number,
    :sku,
    :subject_of,
    :url,
    :valid_from,
    :valid_through,
    :warranty
  ]

  @json_keys %{
    accepted_payment_method: "acceptedPaymentMethod",
    additional_type: "additionalType",
    advance_booking_requirement: "advanceBookingRequirement",
    alternate_name: "alternateName",
    area_served: "areaServed",
    asin: "asin",
    availability: "availability",
    availability_ends: "availabilityEnds",
    availability_starts: "availabilityStarts",
    available_at_or_from: "availableAtOrFrom",
    available_delivery_method: "availableDeliveryMethod",
    business_function: "businessFunction",
    delivery_lead_time: "deliveryLeadTime",
    description: "description",
    disambiguating_description: "disambiguatingDescription",
    eligible_customer_type: "eligibleCustomerType",
    eligible_duration: "eligibleDuration",
    eligible_quantity: "eligibleQuantity",
    eligible_region: "eligibleRegion",
    eligible_transaction_volume: "eligibleTransactionVolume",
    gtin: "gtin",
    gtin12: "gtin12",
    gtin13: "gtin13",
    gtin14: "gtin14",
    gtin8: "gtin8",
    identifier: "identifier",
    image: "image",
    includes_object: "includesObject",
    ineligible_region: "ineligibleRegion",
    inventory_level: "inventoryLevel",
    item_condition: "itemCondition",
    item_offered: "itemOffered",
    main_entity_of_page: "mainEntityOfPage",
    mpn: "mpn",
    name: "name",
    owner: "owner",
    potential_action: "potentialAction",
    price_specification: "priceSpecification",
    same_as: "sameAs",
    seller: "seller",
    serial_number: "serialNumber",
    sku: "sku",
    subject_of: "subjectOf",
    url: "url",
    valid_from: "validFrom",
    valid_through: "validThrough",
    warranty: "warranty"
  }

  @doc false
  def __schema_org__, do: %{type: "Demand", json_keys: @json_keys}

  @doc "Builds an empty `SchemaOrg.Demand` struct."
  def new, do: %__MODULE__{}
end
