defmodule SchemaOrg.Drug do
  @moduledoc "A chemical or biologic substance, used as a medical therapy, that has a physiological effect on an organism. Here the term drug is used interchangeably with the term medicine although clinical knowledge makes a clear difference between them."

  defstruct [
    :active_ingredient,
    :additional_property,
    :additional_type,
    :administration_route,
    :aggregate_rating,
    :alcohol_warning,
    :alternate_name,
    :asin,
    :audience,
    :available_strength,
    :award,
    :awards,
    :brand,
    :breastfeeding_warning,
    :category,
    :clincal_pharmacology,
    :clinical_pharmacology,
    :code,
    :color,
    :color_swatch,
    :country_of_assembly,
    :country_of_last_processing,
    :country_of_origin,
    :depth,
    :description,
    :disambiguating_description,
    :display_location,
    :dosage_form,
    :dose_schedule,
    :drug_class,
    :drug_unit,
    :food_warning,
    :funding,
    :gtin,
    :gtin12,
    :gtin13,
    :gtin14,
    :gtin8,
    :guideline,
    :has_adult_consideration,
    :has_certification,
    :has_energy_consumption_details,
    :has_gs1_digital_link,
    :has_measurement,
    :has_merchant_return_policy,
    :height,
    :identifier,
    :image,
    :in_product_group_with_id,
    :included_in_health_insurance_plan,
    :interacting_drug,
    :is_accessory_or_spare_part_for,
    :is_available_generically,
    :is_consumable_for,
    :is_family_friendly,
    :is_proprietary,
    :is_related_to,
    :is_similar_to,
    :is_variant_of,
    :item_condition,
    :keywords,
    :label_details,
    :legal_status,
    :logo,
    :main_entity_of_page,
    :manufacturer,
    :material,
    :maximum_intake,
    :mechanism_of_action,
    :medicine_system,
    :mobile_url,
    :model,
    :mpn,
    :name,
    :negative_notes,
    :non_proprietary_name,
    :nsn,
    :offers,
    :overdosage,
    :owner,
    :pattern,
    :positive_notes,
    :potential_action,
    :pregnancy_category,
    :pregnancy_warning,
    :prescribing_info,
    :prescription_status,
    :product_id,
    :production_date,
    :proprietary_name,
    :purchase_date,
    :recognizing_authority,
    :related_drug,
    :release_date,
    :relevant_specialty,
    :review,
    :reviews,
    :rxcui,
    :same_as,
    :size,
    :sku,
    :slogan,
    :study,
    :subject_of,
    :url,
    :warning,
    :weight,
    :width
  ]

  @json_keys %{
    active_ingredient: "activeIngredient",
    additional_property: "additionalProperty",
    additional_type: "additionalType",
    administration_route: "administrationRoute",
    aggregate_rating: "aggregateRating",
    alcohol_warning: "alcoholWarning",
    alternate_name: "alternateName",
    asin: "asin",
    audience: "audience",
    available_strength: "availableStrength",
    award: "award",
    awards: "awards",
    brand: "brand",
    breastfeeding_warning: "breastfeedingWarning",
    category: "category",
    clincal_pharmacology: "clincalPharmacology",
    clinical_pharmacology: "clinicalPharmacology",
    code: "code",
    color: "color",
    color_swatch: "colorSwatch",
    country_of_assembly: "countryOfAssembly",
    country_of_last_processing: "countryOfLastProcessing",
    country_of_origin: "countryOfOrigin",
    depth: "depth",
    description: "description",
    disambiguating_description: "disambiguatingDescription",
    display_location: "displayLocation",
    dosage_form: "dosageForm",
    dose_schedule: "doseSchedule",
    drug_class: "drugClass",
    drug_unit: "drugUnit",
    food_warning: "foodWarning",
    funding: "funding",
    gtin: "gtin",
    gtin12: "gtin12",
    gtin13: "gtin13",
    gtin14: "gtin14",
    gtin8: "gtin8",
    guideline: "guideline",
    has_adult_consideration: "hasAdultConsideration",
    has_certification: "hasCertification",
    has_energy_consumption_details: "hasEnergyConsumptionDetails",
    has_gs1_digital_link: "hasGS1DigitalLink",
    has_measurement: "hasMeasurement",
    has_merchant_return_policy: "hasMerchantReturnPolicy",
    height: "height",
    identifier: "identifier",
    image: "image",
    in_product_group_with_id: "inProductGroupWithID",
    included_in_health_insurance_plan: "includedInHealthInsurancePlan",
    interacting_drug: "interactingDrug",
    is_accessory_or_spare_part_for: "isAccessoryOrSparePartFor",
    is_available_generically: "isAvailableGenerically",
    is_consumable_for: "isConsumableFor",
    is_family_friendly: "isFamilyFriendly",
    is_proprietary: "isProprietary",
    is_related_to: "isRelatedTo",
    is_similar_to: "isSimilarTo",
    is_variant_of: "isVariantOf",
    item_condition: "itemCondition",
    keywords: "keywords",
    label_details: "labelDetails",
    legal_status: "legalStatus",
    logo: "logo",
    main_entity_of_page: "mainEntityOfPage",
    manufacturer: "manufacturer",
    material: "material",
    maximum_intake: "maximumIntake",
    mechanism_of_action: "mechanismOfAction",
    medicine_system: "medicineSystem",
    mobile_url: "mobileUrl",
    model: "model",
    mpn: "mpn",
    name: "name",
    negative_notes: "negativeNotes",
    non_proprietary_name: "nonProprietaryName",
    nsn: "nsn",
    offers: "offers",
    overdosage: "overdosage",
    owner: "owner",
    pattern: "pattern",
    positive_notes: "positiveNotes",
    potential_action: "potentialAction",
    pregnancy_category: "pregnancyCategory",
    pregnancy_warning: "pregnancyWarning",
    prescribing_info: "prescribingInfo",
    prescription_status: "prescriptionStatus",
    product_id: "productID",
    production_date: "productionDate",
    proprietary_name: "proprietaryName",
    purchase_date: "purchaseDate",
    recognizing_authority: "recognizingAuthority",
    related_drug: "relatedDrug",
    release_date: "releaseDate",
    relevant_specialty: "relevantSpecialty",
    review: "review",
    reviews: "reviews",
    rxcui: "rxcui",
    same_as: "sameAs",
    size: "size",
    sku: "sku",
    slogan: "slogan",
    study: "study",
    subject_of: "subjectOf",
    url: "url",
    warning: "warning",
    weight: "weight",
    width: "width"
  }

  @doc false
  def __schema_org__, do: %{type: "Drug", json_keys: @json_keys}

  @doc "Builds an empty `SchemaOrg.Drug` struct."
  def new, do: %__MODULE__{}
end
