defmodule SchemaOrg.ExerciseAction do
  @moduledoc "The act of participating in exertive activity for the purposes of improving health and fitness."

  defstruct [
    :action_process,
    :action_status,
    :additional_type,
    :agent,
    :alternate_name,
    :audience,
    :course,
    :description,
    :diet,
    :disambiguating_description,
    :distance,
    :end_time,
    :error,
    :event,
    :exercise_course,
    :exercise_plan,
    :exercise_related_diet,
    :exercise_type,
    :from_location,
    :identifier,
    :image,
    :instrument,
    :location,
    :main_entity_of_page,
    :name,
    :object,
    :opponent,
    :owner,
    :participant,
    :potential_action,
    :provider,
    :result,
    :same_as,
    :sports_activity_location,
    :sports_event,
    :sports_team,
    :start_time,
    :subject_of,
    :target,
    :to_location,
    :url
  ]

  @json_keys %{
    action_process: "actionProcess",
    action_status: "actionStatus",
    additional_type: "additionalType",
    agent: "agent",
    alternate_name: "alternateName",
    audience: "audience",
    course: "course",
    description: "description",
    diet: "diet",
    disambiguating_description: "disambiguatingDescription",
    distance: "distance",
    end_time: "endTime",
    error: "error",
    event: "event",
    exercise_course: "exerciseCourse",
    exercise_plan: "exercisePlan",
    exercise_related_diet: "exerciseRelatedDiet",
    exercise_type: "exerciseType",
    from_location: "fromLocation",
    identifier: "identifier",
    image: "image",
    instrument: "instrument",
    location: "location",
    main_entity_of_page: "mainEntityOfPage",
    name: "name",
    object: "object",
    opponent: "opponent",
    owner: "owner",
    participant: "participant",
    potential_action: "potentialAction",
    provider: "provider",
    result: "result",
    same_as: "sameAs",
    sports_activity_location: "sportsActivityLocation",
    sports_event: "sportsEvent",
    sports_team: "sportsTeam",
    start_time: "startTime",
    subject_of: "subjectOf",
    target: "target",
    to_location: "toLocation",
    url: "url"
  }

  @doc false
  def __schema_org__, do: %{type: "ExerciseAction", json_keys: @json_keys}

  @doc "Builds an empty `SchemaOrg.ExerciseAction` struct."
  def new, do: %__MODULE__{}
end
