defmodule SchemaOrg.InvestmentOrDeposit do
  @moduledoc "A type of financial product that typically requires the client to transfer funds to a financial service in return for potential beneficial financial return."

  defstruct [
    :additional_type,
    :aggregate_rating,
    :alternate_name,
    :amount,
    :annual_percentage_rate,
    :area_served,
    :audience,
    :available_channel,
    :award,
    :brand,
    :broker,
    :category,
    :description,
    :disambiguating_description,
    :fees_and_commissions_specification,
    :has_certification,
    :has_offer_catalog,
    :hours_available,
    :identifier,
    :image,
    :interest_rate,
    :is_related_to,
    :is_similar_to,
    :logo,
    :main_entity_of_page,
    :name,
    :offers,
    :owner,
    :potential_action,
    :produces,
    :provider,
    :provider_mobility,
    :review,
    :same_as,
    :service_area,
    :service_audience,
    :service_output,
    :service_type,
    :slogan,
    :subject_of,
    :terms_of_service,
    :url
  ]

  @json_keys %{
    additional_type: "additionalType",
    aggregate_rating: "aggregateRating",
    alternate_name: "alternateName",
    amount: "amount",
    annual_percentage_rate: "annualPercentageRate",
    area_served: "areaServed",
    audience: "audience",
    available_channel: "availableChannel",
    award: "award",
    brand: "brand",
    broker: "broker",
    category: "category",
    description: "description",
    disambiguating_description: "disambiguatingDescription",
    fees_and_commissions_specification: "feesAndCommissionsSpecification",
    has_certification: "hasCertification",
    has_offer_catalog: "hasOfferCatalog",
    hours_available: "hoursAvailable",
    identifier: "identifier",
    image: "image",
    interest_rate: "interestRate",
    is_related_to: "isRelatedTo",
    is_similar_to: "isSimilarTo",
    logo: "logo",
    main_entity_of_page: "mainEntityOfPage",
    name: "name",
    offers: "offers",
    owner: "owner",
    potential_action: "potentialAction",
    produces: "produces",
    provider: "provider",
    provider_mobility: "providerMobility",
    review: "review",
    same_as: "sameAs",
    service_area: "serviceArea",
    service_audience: "serviceAudience",
    service_output: "serviceOutput",
    service_type: "serviceType",
    slogan: "slogan",
    subject_of: "subjectOf",
    terms_of_service: "termsOfService",
    url: "url"
  }

  @doc false
  def __schema_org__, do: %{type: "InvestmentOrDeposit", json_keys: @json_keys}

  @doc "Builds an empty `SchemaOrg.InvestmentOrDeposit` struct."
  def new, do: %__MODULE__{}
end
