defmodule SchemaOrg.JobPosting do
  @moduledoc "A listing that describes a job opening in a certain organization."

  defstruct [
    :additional_type,
    :alternate_name,
    :applicant_location_requirements,
    :application_contact,
    :base_salary,
    :benefits,
    :date_posted,
    :description,
    :direct_apply,
    :disambiguating_description,
    :education_requirements,
    :eligibility_to_work_requirement,
    :employer_overview,
    :employment_type,
    :employment_unit,
    :estimated_salary,
    :experience_in_place_of_education,
    :experience_requirements,
    :hiring_organization,
    :identifier,
    :image,
    :incentive_compensation,
    :incentives,
    :industry,
    :job_benefits,
    :job_duration,
    :job_immediate_start,
    :job_location,
    :job_location_type,
    :job_start_date,
    :main_entity_of_page,
    :name,
    :occupational_category,
    :owner,
    :physical_requirement,
    :potential_action,
    :qualifications,
    :relevant_occupation,
    :responsibilities,
    :salary_currency,
    :same_as,
    :security_clearance_requirement,
    :sensory_requirement,
    :skills,
    :special_commitments,
    :subject_of,
    :title,
    :total_job_openings,
    :url,
    :valid_through,
    :work_hours
  ]

  @json_keys %{
    additional_type: "additionalType",
    alternate_name: "alternateName",
    applicant_location_requirements: "applicantLocationRequirements",
    application_contact: "applicationContact",
    base_salary: "baseSalary",
    benefits: "benefits",
    date_posted: "datePosted",
    description: "description",
    direct_apply: "directApply",
    disambiguating_description: "disambiguatingDescription",
    education_requirements: "educationRequirements",
    eligibility_to_work_requirement: "eligibilityToWorkRequirement",
    employer_overview: "employerOverview",
    employment_type: "employmentType",
    employment_unit: "employmentUnit",
    estimated_salary: "estimatedSalary",
    experience_in_place_of_education: "experienceInPlaceOfEducation",
    experience_requirements: "experienceRequirements",
    hiring_organization: "hiringOrganization",
    identifier: "identifier",
    image: "image",
    incentive_compensation: "incentiveCompensation",
    incentives: "incentives",
    industry: "industry",
    job_benefits: "jobBenefits",
    job_duration: "jobDuration",
    job_immediate_start: "jobImmediateStart",
    job_location: "jobLocation",
    job_location_type: "jobLocationType",
    job_start_date: "jobStartDate",
    main_entity_of_page: "mainEntityOfPage",
    name: "name",
    occupational_category: "occupationalCategory",
    owner: "owner",
    physical_requirement: "physicalRequirement",
    potential_action: "potentialAction",
    qualifications: "qualifications",
    relevant_occupation: "relevantOccupation",
    responsibilities: "responsibilities",
    salary_currency: "salaryCurrency",
    same_as: "sameAs",
    security_clearance_requirement: "securityClearanceRequirement",
    sensory_requirement: "sensoryRequirement",
    skills: "skills",
    special_commitments: "specialCommitments",
    subject_of: "subjectOf",
    title: "title",
    total_job_openings: "totalJobOpenings",
    url: "url",
    valid_through: "validThrough",
    work_hours: "workHours"
  }

  @doc false
  def __schema_org__, do: %{type: "JobPosting", json_keys: @json_keys}

  @doc "Builds an empty `SchemaOrg.JobPosting` struct."
  def new, do: %__MODULE__{}
end
