defmodule SchemaOrg.MusicGroup do
  @moduledoc "A musical group, such as a band, an orchestra, or a choir. Can also be a solo musician."

  defstruct [
    :accepted_payment_method,
    :actionable_feedback_policy,
    :additional_type,
    :address,
    :agent_interaction_statistic,
    :aggregate_rating,
    :album,
    :albums,
    :alternate_name,
    :alumni,
    :area_served,
    :award,
    :awards,
    :brand,
    :company_registration,
    :contact_point,
    :contact_points,
    :corrections_policy,
    :department,
    :description,
    :disambiguating_description,
    :dissolution_date,
    :diversity_policy,
    :diversity_staffing_report,
    :duns,
    :email,
    :employee,
    :employees,
    :ethics_policy,
    :event,
    :events,
    :fax_number,
    :founder,
    :founders,
    :founding_date,
    :founding_location,
    :funder,
    :funding,
    :genre,
    :global_location_number,
    :has_certification,
    :has_credential,
    :has_gs1_digital_link,
    :has_member_program,
    :has_merchant_return_policy,
    :has_offer_catalog,
    :has_pos,
    :has_shipping_service,
    :identifier,
    :image,
    :interaction_statistic,
    :isic_v4,
    :iso6523_code,
    :keywords,
    :knows_about,
    :knows_language,
    :legal_address,
    :legal_name,
    :legal_representative,
    :lei_code,
    :location,
    :logo,
    :main_entity_of_page,
    :makes_offer,
    :member,
    :member_of,
    :members,
    :music_group_member,
    :naics,
    :name,
    :nonprofit_status,
    :number_of_employees,
    :owner,
    :ownership_funding_info,
    :owns,
    :parent_organization,
    :potential_action,
    :publishing_principles,
    :review,
    :reviews,
    :same_as,
    :seeks,
    :service_area,
    :skills,
    :slogan,
    :sponsor,
    :sub_organization,
    :subject_of,
    :tax_id,
    :telephone,
    :track,
    :tracks,
    :unnamed_sources_policy,
    :url,
    :vat_id
  ]

  @json_keys %{
    accepted_payment_method: "acceptedPaymentMethod",
    actionable_feedback_policy: "actionableFeedbackPolicy",
    additional_type: "additionalType",
    address: "address",
    agent_interaction_statistic: "agentInteractionStatistic",
    aggregate_rating: "aggregateRating",
    album: "album",
    albums: "albums",
    alternate_name: "alternateName",
    alumni: "alumni",
    area_served: "areaServed",
    award: "award",
    awards: "awards",
    brand: "brand",
    company_registration: "companyRegistration",
    contact_point: "contactPoint",
    contact_points: "contactPoints",
    corrections_policy: "correctionsPolicy",
    department: "department",
    description: "description",
    disambiguating_description: "disambiguatingDescription",
    dissolution_date: "dissolutionDate",
    diversity_policy: "diversityPolicy",
    diversity_staffing_report: "diversityStaffingReport",
    duns: "duns",
    email: "email",
    employee: "employee",
    employees: "employees",
    ethics_policy: "ethicsPolicy",
    event: "event",
    events: "events",
    fax_number: "faxNumber",
    founder: "founder",
    founders: "founders",
    founding_date: "foundingDate",
    founding_location: "foundingLocation",
    funder: "funder",
    funding: "funding",
    genre: "genre",
    global_location_number: "globalLocationNumber",
    has_certification: "hasCertification",
    has_credential: "hasCredential",
    has_gs1_digital_link: "hasGS1DigitalLink",
    has_member_program: "hasMemberProgram",
    has_merchant_return_policy: "hasMerchantReturnPolicy",
    has_offer_catalog: "hasOfferCatalog",
    has_pos: "hasPOS",
    has_shipping_service: "hasShippingService",
    identifier: "identifier",
    image: "image",
    interaction_statistic: "interactionStatistic",
    isic_v4: "isicV4",
    iso6523_code: "iso6523Code",
    keywords: "keywords",
    knows_about: "knowsAbout",
    knows_language: "knowsLanguage",
    legal_address: "legalAddress",
    legal_name: "legalName",
    legal_representative: "legalRepresentative",
    lei_code: "leiCode",
    location: "location",
    logo: "logo",
    main_entity_of_page: "mainEntityOfPage",
    makes_offer: "makesOffer",
    member: "member",
    member_of: "memberOf",
    members: "members",
    music_group_member: "musicGroupMember",
    naics: "naics",
    name: "name",
    nonprofit_status: "nonprofitStatus",
    number_of_employees: "numberOfEmployees",
    owner: "owner",
    ownership_funding_info: "ownershipFundingInfo",
    owns: "owns",
    parent_organization: "parentOrganization",
    potential_action: "potentialAction",
    publishing_principles: "publishingPrinciples",
    review: "review",
    reviews: "reviews",
    same_as: "sameAs",
    seeks: "seeks",
    service_area: "serviceArea",
    skills: "skills",
    slogan: "slogan",
    sponsor: "sponsor",
    sub_organization: "subOrganization",
    subject_of: "subjectOf",
    tax_id: "taxID",
    telephone: "telephone",
    track: "track",
    tracks: "tracks",
    unnamed_sources_policy: "unnamedSourcesPolicy",
    url: "url",
    vat_id: "vatID"
  }

  @doc false
  def __schema_org__, do: %{type: "MusicGroup", json_keys: @json_keys}

  @doc "Builds an empty `SchemaOrg.MusicGroup` struct."
  def new, do: %__MODULE__{}
end
