defmodule SchemaOrg.Patient do
  @moduledoc "A patient is any person recipient of health care services."

  defstruct [
    :additional_name,
    :additional_type,
    :address,
    :affiliation,
    :agent_interaction_statistic,
    :alternate_name,
    :alumni_of,
    :audience_type,
    :award,
    :awards,
    :birth_date,
    :birth_place,
    :brand,
    :call_sign,
    :children,
    :colleague,
    :colleagues,
    :contact_point,
    :contact_points,
    :death_date,
    :death_place,
    :description,
    :diagnosis,
    :disambiguating_description,
    :drug,
    :duns,
    :email,
    :family_name,
    :fax_number,
    :follows,
    :funder,
    :funding,
    :gender,
    :geographic_area,
    :given_name,
    :global_location_number,
    :has_certification,
    :has_credential,
    :has_occupation,
    :has_offer_catalog,
    :has_pos,
    :health_condition,
    :height,
    :home_location,
    :honorific_prefix,
    :honorific_suffix,
    :identifier,
    :image,
    :interaction_statistic,
    :isic_v4,
    :job_title,
    :knows,
    :knows_about,
    :knows_language,
    :life_event,
    :main_entity_of_page,
    :makes_offer,
    :member_of,
    :naics,
    :name,
    :nationality,
    :net_worth,
    :owner,
    :owns,
    :parent,
    :parents,
    :performer_in,
    :potential_action,
    :pronouns,
    :publishing_principles,
    :related_to,
    :required_gender,
    :required_max_age,
    :required_min_age,
    :same_as,
    :seeks,
    :sibling,
    :siblings,
    :skills,
    :sponsor,
    :spouse,
    :subject_of,
    :suggested_age,
    :suggested_gender,
    :suggested_max_age,
    :suggested_measurement,
    :suggested_min_age,
    :tax_id,
    :telephone,
    :url,
    :vat_id,
    :weight,
    :work_location,
    :works_for
  ]

  @json_keys %{
    additional_name: "additionalName",
    additional_type: "additionalType",
    address: "address",
    affiliation: "affiliation",
    agent_interaction_statistic: "agentInteractionStatistic",
    alternate_name: "alternateName",
    alumni_of: "alumniOf",
    audience_type: "audienceType",
    award: "award",
    awards: "awards",
    birth_date: "birthDate",
    birth_place: "birthPlace",
    brand: "brand",
    call_sign: "callSign",
    children: "children",
    colleague: "colleague",
    colleagues: "colleagues",
    contact_point: "contactPoint",
    contact_points: "contactPoints",
    death_date: "deathDate",
    death_place: "deathPlace",
    description: "description",
    diagnosis: "diagnosis",
    disambiguating_description: "disambiguatingDescription",
    drug: "drug",
    duns: "duns",
    email: "email",
    family_name: "familyName",
    fax_number: "faxNumber",
    follows: "follows",
    funder: "funder",
    funding: "funding",
    gender: "gender",
    geographic_area: "geographicArea",
    given_name: "givenName",
    global_location_number: "globalLocationNumber",
    has_certification: "hasCertification",
    has_credential: "hasCredential",
    has_occupation: "hasOccupation",
    has_offer_catalog: "hasOfferCatalog",
    has_pos: "hasPOS",
    health_condition: "healthCondition",
    height: "height",
    home_location: "homeLocation",
    honorific_prefix: "honorificPrefix",
    honorific_suffix: "honorificSuffix",
    identifier: "identifier",
    image: "image",
    interaction_statistic: "interactionStatistic",
    isic_v4: "isicV4",
    job_title: "jobTitle",
    knows: "knows",
    knows_about: "knowsAbout",
    knows_language: "knowsLanguage",
    life_event: "lifeEvent",
    main_entity_of_page: "mainEntityOfPage",
    makes_offer: "makesOffer",
    member_of: "memberOf",
    naics: "naics",
    name: "name",
    nationality: "nationality",
    net_worth: "netWorth",
    owner: "owner",
    owns: "owns",
    parent: "parent",
    parents: "parents",
    performer_in: "performerIn",
    potential_action: "potentialAction",
    pronouns: "pronouns",
    publishing_principles: "publishingPrinciples",
    related_to: "relatedTo",
    required_gender: "requiredGender",
    required_max_age: "requiredMaxAge",
    required_min_age: "requiredMinAge",
    same_as: "sameAs",
    seeks: "seeks",
    sibling: "sibling",
    siblings: "siblings",
    skills: "skills",
    sponsor: "sponsor",
    spouse: "spouse",
    subject_of: "subjectOf",
    suggested_age: "suggestedAge",
    suggested_gender: "suggestedGender",
    suggested_max_age: "suggestedMaxAge",
    suggested_measurement: "suggestedMeasurement",
    suggested_min_age: "suggestedMinAge",
    tax_id: "taxID",
    telephone: "telephone",
    url: "url",
    vat_id: "vatID",
    weight: "weight",
    work_location: "workLocation",
    works_for: "worksFor"
  }

  @doc false
  def __schema_org__, do: %{type: "Patient", json_keys: @json_keys}

  @doc "Builds an empty `SchemaOrg.Patient` struct."
  def new, do: %__MODULE__{}
end
