defmodule SchemaOrg.ProductCollection do
  @moduledoc "A set of products (either `ProductGroup`s or specific variants) that are listed together e.g. in an `Offer`."

  defstruct [
    :about,
    :abstract,
    :access_mode,
    :access_mode_sufficient,
    :accessibility_api,
    :accessibility_control,
    :accessibility_feature,
    :accessibility_hazard,
    :accessibility_summary,
    :accountable_person,
    :acquire_license_page,
    :additional_property,
    :additional_type,
    :aggregate_rating,
    :alternate_name,
    :alternative_headline,
    :archived_at,
    :asin,
    :assesses,
    :associated_media,
    :audience,
    :audio,
    :author,
    :award,
    :awards,
    :brand,
    :category,
    :character,
    :citation,
    :collection_size,
    :color,
    :color_swatch,
    :comment,
    :comment_count,
    :conditions_of_access,
    :content_location,
    :content_rating,
    :content_reference_time,
    :contributor,
    :copyright_holder,
    :copyright_notice,
    :copyright_year,
    :correction,
    :country_of_assembly,
    :country_of_last_processing,
    :country_of_origin,
    :creative_work_status,
    :creator,
    :credit_text,
    :date_created,
    :date_modified,
    :date_published,
    :depth,
    :description,
    :digital_source_type,
    :disambiguating_description,
    :discussion_url,
    :display_location,
    :edit_eidr,
    :editor,
    :educational_alignment,
    :educational_level,
    :educational_use,
    :encoding,
    :encoding_format,
    :encodings,
    :example_of_work,
    :expires,
    :file_format,
    :funder,
    :funding,
    :genre,
    :gtin,
    :gtin12,
    :gtin13,
    :gtin14,
    :gtin8,
    :has_adult_consideration,
    :has_certification,
    :has_energy_consumption_details,
    :has_gs1_digital_link,
    :has_measurement,
    :has_merchant_return_policy,
    :has_part,
    :headline,
    :height,
    :identifier,
    :image,
    :in_language,
    :in_product_group_with_id,
    :includes_object,
    :interaction_statistic,
    :interactivity_type,
    :interpreted_as_claim,
    :is_accessible_for_free,
    :is_accessory_or_spare_part_for,
    :is_based_on,
    :is_based_on_url,
    :is_consumable_for,
    :is_family_friendly,
    :is_part_of,
    :is_related_to,
    :is_similar_to,
    :is_variant_of,
    :item_condition,
    :keywords,
    :learning_resource_type,
    :license,
    :location_created,
    :logo,
    :main_entity,
    :main_entity_of_page,
    :maintainer,
    :manufacturer,
    :material,
    :material_extent,
    :mentions,
    :mobile_url,
    :model,
    :mpn,
    :name,
    :negative_notes,
    :nsn,
    :offers,
    :owner,
    :pattern,
    :position,
    :positive_notes,
    :potential_action,
    :producer,
    :product_id,
    :production_date,
    :provider,
    :publication,
    :publisher,
    :publisher_imprint,
    :publishing_principles,
    :purchase_date,
    :recorded_at,
    :release_date,
    :released_event,
    :review,
    :reviews,
    :same_as,
    :schema_version,
    :sd_date_published,
    :sd_license,
    :sd_publisher,
    :size,
    :sku,
    :slogan,
    :source_organization,
    :spatial,
    :spatial_coverage,
    :sponsor,
    :subject_of,
    :teaches,
    :temporal,
    :temporal_coverage,
    :text,
    :thumbnail,
    :thumbnail_url,
    :time_required,
    :translation_of_work,
    :translator,
    :typical_age_range,
    :url,
    :usage_info,
    :version,
    :video,
    :weight,
    :width,
    :word_count,
    :work_example,
    :work_translation
  ]

  @json_keys %{
    about: "about",
    abstract: "abstract",
    access_mode: "accessMode",
    access_mode_sufficient: "accessModeSufficient",
    accessibility_api: "accessibilityAPI",
    accessibility_control: "accessibilityControl",
    accessibility_feature: "accessibilityFeature",
    accessibility_hazard: "accessibilityHazard",
    accessibility_summary: "accessibilitySummary",
    accountable_person: "accountablePerson",
    acquire_license_page: "acquireLicensePage",
    additional_property: "additionalProperty",
    additional_type: "additionalType",
    aggregate_rating: "aggregateRating",
    alternate_name: "alternateName",
    alternative_headline: "alternativeHeadline",
    archived_at: "archivedAt",
    asin: "asin",
    assesses: "assesses",
    associated_media: "associatedMedia",
    audience: "audience",
    audio: "audio",
    author: "author",
    award: "award",
    awards: "awards",
    brand: "brand",
    category: "category",
    character: "character",
    citation: "citation",
    collection_size: "collectionSize",
    color: "color",
    color_swatch: "colorSwatch",
    comment: "comment",
    comment_count: "commentCount",
    conditions_of_access: "conditionsOfAccess",
    content_location: "contentLocation",
    content_rating: "contentRating",
    content_reference_time: "contentReferenceTime",
    contributor: "contributor",
    copyright_holder: "copyrightHolder",
    copyright_notice: "copyrightNotice",
    copyright_year: "copyrightYear",
    correction: "correction",
    country_of_assembly: "countryOfAssembly",
    country_of_last_processing: "countryOfLastProcessing",
    country_of_origin: "countryOfOrigin",
    creative_work_status: "creativeWorkStatus",
    creator: "creator",
    credit_text: "creditText",
    date_created: "dateCreated",
    date_modified: "dateModified",
    date_published: "datePublished",
    depth: "depth",
    description: "description",
    digital_source_type: "digitalSourceType",
    disambiguating_description: "disambiguatingDescription",
    discussion_url: "discussionUrl",
    display_location: "displayLocation",
    edit_eidr: "editEIDR",
    editor: "editor",
    educational_alignment: "educationalAlignment",
    educational_level: "educationalLevel",
    educational_use: "educationalUse",
    encoding: "encoding",
    encoding_format: "encodingFormat",
    encodings: "encodings",
    example_of_work: "exampleOfWork",
    expires: "expires",
    file_format: "fileFormat",
    funder: "funder",
    funding: "funding",
    genre: "genre",
    gtin: "gtin",
    gtin12: "gtin12",
    gtin13: "gtin13",
    gtin14: "gtin14",
    gtin8: "gtin8",
    has_adult_consideration: "hasAdultConsideration",
    has_certification: "hasCertification",
    has_energy_consumption_details: "hasEnergyConsumptionDetails",
    has_gs1_digital_link: "hasGS1DigitalLink",
    has_measurement: "hasMeasurement",
    has_merchant_return_policy: "hasMerchantReturnPolicy",
    has_part: "hasPart",
    headline: "headline",
    height: "height",
    identifier: "identifier",
    image: "image",
    in_language: "inLanguage",
    in_product_group_with_id: "inProductGroupWithID",
    includes_object: "includesObject",
    interaction_statistic: "interactionStatistic",
    interactivity_type: "interactivityType",
    interpreted_as_claim: "interpretedAsClaim",
    is_accessible_for_free: "isAccessibleForFree",
    is_accessory_or_spare_part_for: "isAccessoryOrSparePartFor",
    is_based_on: "isBasedOn",
    is_based_on_url: "isBasedOnUrl",
    is_consumable_for: "isConsumableFor",
    is_family_friendly: "isFamilyFriendly",
    is_part_of: "isPartOf",
    is_related_to: "isRelatedTo",
    is_similar_to: "isSimilarTo",
    is_variant_of: "isVariantOf",
    item_condition: "itemCondition",
    keywords: "keywords",
    learning_resource_type: "learningResourceType",
    license: "license",
    location_created: "locationCreated",
    logo: "logo",
    main_entity: "mainEntity",
    main_entity_of_page: "mainEntityOfPage",
    maintainer: "maintainer",
    manufacturer: "manufacturer",
    material: "material",
    material_extent: "materialExtent",
    mentions: "mentions",
    mobile_url: "mobileUrl",
    model: "model",
    mpn: "mpn",
    name: "name",
    negative_notes: "negativeNotes",
    nsn: "nsn",
    offers: "offers",
    owner: "owner",
    pattern: "pattern",
    position: "position",
    positive_notes: "positiveNotes",
    potential_action: "potentialAction",
    producer: "producer",
    product_id: "productID",
    production_date: "productionDate",
    provider: "provider",
    publication: "publication",
    publisher: "publisher",
    publisher_imprint: "publisherImprint",
    publishing_principles: "publishingPrinciples",
    purchase_date: "purchaseDate",
    recorded_at: "recordedAt",
    release_date: "releaseDate",
    released_event: "releasedEvent",
    review: "review",
    reviews: "reviews",
    same_as: "sameAs",
    schema_version: "schemaVersion",
    sd_date_published: "sdDatePublished",
    sd_license: "sdLicense",
    sd_publisher: "sdPublisher",
    size: "size",
    sku: "sku",
    slogan: "slogan",
    source_organization: "sourceOrganization",
    spatial: "spatial",
    spatial_coverage: "spatialCoverage",
    sponsor: "sponsor",
    subject_of: "subjectOf",
    teaches: "teaches",
    temporal: "temporal",
    temporal_coverage: "temporalCoverage",
    text: "text",
    thumbnail: "thumbnail",
    thumbnail_url: "thumbnailUrl",
    time_required: "timeRequired",
    translation_of_work: "translationOfWork",
    translator: "translator",
    typical_age_range: "typicalAgeRange",
    url: "url",
    usage_info: "usageInfo",
    version: "version",
    video: "video",
    weight: "weight",
    width: "width",
    word_count: "wordCount",
    work_example: "workExample",
    work_translation: "workTranslation"
  }

  @doc false
  def __schema_org__, do: %{type: "ProductCollection", json_keys: @json_keys}

  @doc "Builds an empty `SchemaOrg.ProductCollection` struct."
  def new, do: %__MODULE__{}
end
