defmodule SchemaOrg.ProductGroup do
  @moduledoc "A ProductGroup represents a group of [[Product]]s that vary only in certain well-described ways, such as by [[size]], [[color]], [[material]] etc.\n\nWhile a ProductGroup itself is not directly offered for sale, the various varying products that it represents can be. The ProductGroup serves as a prototype or template, standing in for all of the products who have an [[isVariantOf]] relationship to it. As such, properties (including additional types) can be applied to the ProductGroup to represent characteristics shared by each of the (possibly very many) variants. Properties that reference a ProductGroup are not included in this mechanism; neither are the following specific properties [[variesBy]], [[hasVariant]], [[url]]. "

  defstruct [
    :additional_property,
    :additional_type,
    :aggregate_rating,
    :alternate_name,
    :asin,
    :audience,
    :award,
    :awards,
    :brand,
    :category,
    :color,
    :color_swatch,
    :country_of_assembly,
    :country_of_last_processing,
    :country_of_origin,
    :depth,
    :description,
    :disambiguating_description,
    :display_location,
    :funding,
    :gtin,
    :gtin12,
    :gtin13,
    :gtin14,
    :gtin8,
    :has_adult_consideration,
    :has_certification,
    :has_energy_consumption_details,
    :has_gs1_digital_link,
    :has_measurement,
    :has_merchant_return_policy,
    :has_variant,
    :height,
    :identifier,
    :image,
    :in_product_group_with_id,
    :is_accessory_or_spare_part_for,
    :is_consumable_for,
    :is_family_friendly,
    :is_related_to,
    :is_similar_to,
    :is_variant_of,
    :item_condition,
    :keywords,
    :logo,
    :main_entity_of_page,
    :manufacturer,
    :material,
    :mobile_url,
    :model,
    :mpn,
    :name,
    :negative_notes,
    :nsn,
    :offers,
    :owner,
    :pattern,
    :positive_notes,
    :potential_action,
    :product_group_id,
    :product_id,
    :production_date,
    :purchase_date,
    :release_date,
    :review,
    :reviews,
    :same_as,
    :size,
    :sku,
    :slogan,
    :subject_of,
    :url,
    :varies_by,
    :weight,
    :width
  ]

  @json_keys %{
    additional_property: "additionalProperty",
    additional_type: "additionalType",
    aggregate_rating: "aggregateRating",
    alternate_name: "alternateName",
    asin: "asin",
    audience: "audience",
    award: "award",
    awards: "awards",
    brand: "brand",
    category: "category",
    color: "color",
    color_swatch: "colorSwatch",
    country_of_assembly: "countryOfAssembly",
    country_of_last_processing: "countryOfLastProcessing",
    country_of_origin: "countryOfOrigin",
    depth: "depth",
    description: "description",
    disambiguating_description: "disambiguatingDescription",
    display_location: "displayLocation",
    funding: "funding",
    gtin: "gtin",
    gtin12: "gtin12",
    gtin13: "gtin13",
    gtin14: "gtin14",
    gtin8: "gtin8",
    has_adult_consideration: "hasAdultConsideration",
    has_certification: "hasCertification",
    has_energy_consumption_details: "hasEnergyConsumptionDetails",
    has_gs1_digital_link: "hasGS1DigitalLink",
    has_measurement: "hasMeasurement",
    has_merchant_return_policy: "hasMerchantReturnPolicy",
    has_variant: "hasVariant",
    height: "height",
    identifier: "identifier",
    image: "image",
    in_product_group_with_id: "inProductGroupWithID",
    is_accessory_or_spare_part_for: "isAccessoryOrSparePartFor",
    is_consumable_for: "isConsumableFor",
    is_family_friendly: "isFamilyFriendly",
    is_related_to: "isRelatedTo",
    is_similar_to: "isSimilarTo",
    is_variant_of: "isVariantOf",
    item_condition: "itemCondition",
    keywords: "keywords",
    logo: "logo",
    main_entity_of_page: "mainEntityOfPage",
    manufacturer: "manufacturer",
    material: "material",
    mobile_url: "mobileUrl",
    model: "model",
    mpn: "mpn",
    name: "name",
    negative_notes: "negativeNotes",
    nsn: "nsn",
    offers: "offers",
    owner: "owner",
    pattern: "pattern",
    positive_notes: "positiveNotes",
    potential_action: "potentialAction",
    product_group_id: "productGroupID",
    product_id: "productID",
    production_date: "productionDate",
    purchase_date: "purchaseDate",
    release_date: "releaseDate",
    review: "review",
    reviews: "reviews",
    same_as: "sameAs",
    size: "size",
    sku: "sku",
    slogan: "slogan",
    subject_of: "subjectOf",
    url: "url",
    varies_by: "variesBy",
    weight: "weight",
    width: "width"
  }

  @doc false
  def __schema_org__, do: %{type: "ProductGroup", json_keys: @json_keys}

  @doc "Builds an empty `SchemaOrg.ProductGroup` struct."
  def new, do: %__MODULE__{}
end
