defmodule SchemaOrg.RuntimePlatform do
  @moduledoc "Specialized software environment that provides the essential infrastructure, libraries, and services required to execute a program."

  defstruct [
    :about,
    :abstract,
    :access_mode,
    :access_mode_sufficient,
    :accessibility_api,
    :accessibility_control,
    :accessibility_feature,
    :accessibility_hazard,
    :accessibility_summary,
    :accountable_person,
    :acquire_license_page,
    :additional_type,
    :aggregate_rating,
    :alternate_name,
    :alternative_headline,
    :application_category,
    :application_sub_category,
    :application_suite,
    :archived_at,
    :assesses,
    :associated_media,
    :audience,
    :audio,
    :author,
    :available_on_device,
    :award,
    :awards,
    :character,
    :citation,
    :comment,
    :comment_count,
    :conditions_of_access,
    :content_location,
    :content_rating,
    :content_reference_time,
    :contributor,
    :copyright_holder,
    :copyright_notice,
    :copyright_year,
    :correction,
    :countries_not_supported,
    :countries_supported,
    :country_of_origin,
    :creative_work_status,
    :creator,
    :credit_text,
    :date_created,
    :date_modified,
    :date_published,
    :description,
    :device,
    :digital_source_type,
    :disambiguating_description,
    :discussion_url,
    :display_location,
    :download_url,
    :edit_eidr,
    :editor,
    :educational_alignment,
    :educational_level,
    :educational_use,
    :encoding,
    :encoding_format,
    :encodings,
    :example_of_work,
    :expires,
    :feature_list,
    :file_format,
    :file_size,
    :funder,
    :funding,
    :genre,
    :has_part,
    :headline,
    :identifier,
    :image,
    :in_language,
    :install_url,
    :interaction_statistic,
    :interactivity_type,
    :interpreted_as_claim,
    :is_accessible_for_free,
    :is_based_on,
    :is_based_on_url,
    :is_family_friendly,
    :is_part_of,
    :keywords,
    :learning_resource_type,
    :license,
    :location_created,
    :main_entity,
    :main_entity_of_page,
    :maintainer,
    :material,
    :material_extent,
    :memory_requirements,
    :mentions,
    :name,
    :offers,
    :operating_system,
    :owner,
    :pattern,
    :permissions,
    :position,
    :potential_action,
    :processor_requirements,
    :producer,
    :provider,
    :publication,
    :publisher,
    :publisher_imprint,
    :publishing_principles,
    :recorded_at,
    :release_notes,
    :released_event,
    :requirements,
    :review,
    :reviews,
    :runtime_platform,
    :same_as,
    :schema_version,
    :screenshot,
    :sd_date_published,
    :sd_license,
    :sd_publisher,
    :size,
    :software_add_on,
    :software_help,
    :software_requirements,
    :software_version,
    :source_organization,
    :spatial,
    :spatial_coverage,
    :sponsor,
    :storage_requirements,
    :subject_of,
    :supporting_data,
    :teaches,
    :temporal,
    :temporal_coverage,
    :text,
    :thumbnail,
    :thumbnail_url,
    :time_required,
    :translation_of_work,
    :translator,
    :typical_age_range,
    :url,
    :usage_info,
    :version,
    :video,
    :word_count,
    :work_example,
    :work_translation
  ]

  @json_keys %{
    about: "about",
    abstract: "abstract",
    access_mode: "accessMode",
    access_mode_sufficient: "accessModeSufficient",
    accessibility_api: "accessibilityAPI",
    accessibility_control: "accessibilityControl",
    accessibility_feature: "accessibilityFeature",
    accessibility_hazard: "accessibilityHazard",
    accessibility_summary: "accessibilitySummary",
    accountable_person: "accountablePerson",
    acquire_license_page: "acquireLicensePage",
    additional_type: "additionalType",
    aggregate_rating: "aggregateRating",
    alternate_name: "alternateName",
    alternative_headline: "alternativeHeadline",
    application_category: "applicationCategory",
    application_sub_category: "applicationSubCategory",
    application_suite: "applicationSuite",
    archived_at: "archivedAt",
    assesses: "assesses",
    associated_media: "associatedMedia",
    audience: "audience",
    audio: "audio",
    author: "author",
    available_on_device: "availableOnDevice",
    award: "award",
    awards: "awards",
    character: "character",
    citation: "citation",
    comment: "comment",
    comment_count: "commentCount",
    conditions_of_access: "conditionsOfAccess",
    content_location: "contentLocation",
    content_rating: "contentRating",
    content_reference_time: "contentReferenceTime",
    contributor: "contributor",
    copyright_holder: "copyrightHolder",
    copyright_notice: "copyrightNotice",
    copyright_year: "copyrightYear",
    correction: "correction",
    countries_not_supported: "countriesNotSupported",
    countries_supported: "countriesSupported",
    country_of_origin: "countryOfOrigin",
    creative_work_status: "creativeWorkStatus",
    creator: "creator",
    credit_text: "creditText",
    date_created: "dateCreated",
    date_modified: "dateModified",
    date_published: "datePublished",
    description: "description",
    device: "device",
    digital_source_type: "digitalSourceType",
    disambiguating_description: "disambiguatingDescription",
    discussion_url: "discussionUrl",
    display_location: "displayLocation",
    download_url: "downloadUrl",
    edit_eidr: "editEIDR",
    editor: "editor",
    educational_alignment: "educationalAlignment",
    educational_level: "educationalLevel",
    educational_use: "educationalUse",
    encoding: "encoding",
    encoding_format: "encodingFormat",
    encodings: "encodings",
    example_of_work: "exampleOfWork",
    expires: "expires",
    feature_list: "featureList",
    file_format: "fileFormat",
    file_size: "fileSize",
    funder: "funder",
    funding: "funding",
    genre: "genre",
    has_part: "hasPart",
    headline: "headline",
    identifier: "identifier",
    image: "image",
    in_language: "inLanguage",
    install_url: "installUrl",
    interaction_statistic: "interactionStatistic",
    interactivity_type: "interactivityType",
    interpreted_as_claim: "interpretedAsClaim",
    is_accessible_for_free: "isAccessibleForFree",
    is_based_on: "isBasedOn",
    is_based_on_url: "isBasedOnUrl",
    is_family_friendly: "isFamilyFriendly",
    is_part_of: "isPartOf",
    keywords: "keywords",
    learning_resource_type: "learningResourceType",
    license: "license",
    location_created: "locationCreated",
    main_entity: "mainEntity",
    main_entity_of_page: "mainEntityOfPage",
    maintainer: "maintainer",
    material: "material",
    material_extent: "materialExtent",
    memory_requirements: "memoryRequirements",
    mentions: "mentions",
    name: "name",
    offers: "offers",
    operating_system: "operatingSystem",
    owner: "owner",
    pattern: "pattern",
    permissions: "permissions",
    position: "position",
    potential_action: "potentialAction",
    processor_requirements: "processorRequirements",
    producer: "producer",
    provider: "provider",
    publication: "publication",
    publisher: "publisher",
    publisher_imprint: "publisherImprint",
    publishing_principles: "publishingPrinciples",
    recorded_at: "recordedAt",
    release_notes: "releaseNotes",
    released_event: "releasedEvent",
    requirements: "requirements",
    review: "review",
    reviews: "reviews",
    runtime_platform: "runtimePlatform",
    same_as: "sameAs",
    schema_version: "schemaVersion",
    screenshot: "screenshot",
    sd_date_published: "sdDatePublished",
    sd_license: "sdLicense",
    sd_publisher: "sdPublisher",
    size: "size",
    software_add_on: "softwareAddOn",
    software_help: "softwareHelp",
    software_requirements: "softwareRequirements",
    software_version: "softwareVersion",
    source_organization: "sourceOrganization",
    spatial: "spatial",
    spatial_coverage: "spatialCoverage",
    sponsor: "sponsor",
    storage_requirements: "storageRequirements",
    subject_of: "subjectOf",
    supporting_data: "supportingData",
    teaches: "teaches",
    temporal: "temporal",
    temporal_coverage: "temporalCoverage",
    text: "text",
    thumbnail: "thumbnail",
    thumbnail_url: "thumbnailUrl",
    time_required: "timeRequired",
    translation_of_work: "translationOfWork",
    translator: "translator",
    typical_age_range: "typicalAgeRange",
    url: "url",
    usage_info: "usageInfo",
    version: "version",
    video: "video",
    word_count: "wordCount",
    work_example: "workExample",
    work_translation: "workTranslation"
  }

  @doc false
  def __schema_org__, do: %{type: "RuntimePlatform", json_keys: @json_keys}

  @doc "Builds an empty `SchemaOrg.RuntimePlatform` struct."
  def new, do: %__MODULE__{}
end
