defmodule SchemaOrg.SequentialArt do
  @moduledoc "An art forms that use images deployed in a specific order for the purpose of graphic storytelling (i.e., narration of graphic stories) or conveying information. Examples of SequentialArt are Franco-Belgian Bande Dessinée, Comics in the USA and 漫画 (Manga) in Japan."

  defstruct [
    :about,
    :abridged,
    :abstract,
    :access_mode,
    :access_mode_sufficient,
    :accessibility_api,
    :accessibility_control,
    :accessibility_feature,
    :accessibility_hazard,
    :accessibility_summary,
    :accountable_person,
    :acquire_license_page,
    :additional_type,
    :aggregate_rating,
    :alternate_name,
    :alternative_headline,
    :archived_at,
    :art_edition,
    :art_medium,
    :artform,
    :artist,
    :artwork_surface,
    :assesses,
    :associated_media,
    :audience,
    :audio,
    :author,
    :award,
    :awards,
    :book_edition,
    :book_format,
    :character,
    :citation,
    :colorist,
    :comment,
    :comment_count,
    :conditions_of_access,
    :content_location,
    :content_rating,
    :content_reference_time,
    :contributor,
    :copyright_holder,
    :copyright_notice,
    :copyright_year,
    :correction,
    :country_of_origin,
    :creative_work_status,
    :creator,
    :credit_text,
    :date_created,
    :date_modified,
    :date_published,
    :depth,
    :description,
    :digital_source_type,
    :disambiguating_description,
    :discussion_url,
    :display_location,
    :edit_eidr,
    :editor,
    :educational_alignment,
    :educational_level,
    :educational_use,
    :encoding,
    :encoding_format,
    :encodings,
    :example_of_work,
    :expires,
    :file_format,
    :funder,
    :funding,
    :genre,
    :has_part,
    :headline,
    :height,
    :identifier,
    :illustrator,
    :image,
    :in_language,
    :inker,
    :interaction_statistic,
    :interactivity_type,
    :interpreted_as_claim,
    :is_accessible_for_free,
    :is_based_on,
    :is_based_on_url,
    :is_family_friendly,
    :is_part_of,
    :isbn,
    :keywords,
    :learning_resource_type,
    :letterer,
    :license,
    :location_created,
    :main_entity,
    :main_entity_of_page,
    :maintainer,
    :material,
    :material_extent,
    :mentions,
    :name,
    :number_of_pages,
    :offers,
    :owner,
    :pattern,
    :penciler,
    :position,
    :potential_action,
    :producer,
    :provider,
    :publication,
    :publisher,
    :publisher_imprint,
    :publishing_principles,
    :recorded_at,
    :released_event,
    :review,
    :reviews,
    :same_as,
    :schema_version,
    :sd_date_published,
    :sd_license,
    :sd_publisher,
    :size,
    :source_organization,
    :spatial,
    :spatial_coverage,
    :sponsor,
    :subject_of,
    :surface,
    :teaches,
    :temporal,
    :temporal_coverage,
    :text,
    :thumbnail,
    :thumbnail_url,
    :time_required,
    :translation_of_work,
    :translator,
    :typical_age_range,
    :url,
    :usage_info,
    :version,
    :video,
    :weight,
    :width,
    :word_count,
    :work_example,
    :work_translation
  ]

  @json_keys %{
    about: "about",
    abridged: "abridged",
    abstract: "abstract",
    access_mode: "accessMode",
    access_mode_sufficient: "accessModeSufficient",
    accessibility_api: "accessibilityAPI",
    accessibility_control: "accessibilityControl",
    accessibility_feature: "accessibilityFeature",
    accessibility_hazard: "accessibilityHazard",
    accessibility_summary: "accessibilitySummary",
    accountable_person: "accountablePerson",
    acquire_license_page: "acquireLicensePage",
    additional_type: "additionalType",
    aggregate_rating: "aggregateRating",
    alternate_name: "alternateName",
    alternative_headline: "alternativeHeadline",
    archived_at: "archivedAt",
    art_edition: "artEdition",
    art_medium: "artMedium",
    artform: "artform",
    artist: "artist",
    artwork_surface: "artworkSurface",
    assesses: "assesses",
    associated_media: "associatedMedia",
    audience: "audience",
    audio: "audio",
    author: "author",
    award: "award",
    awards: "awards",
    book_edition: "bookEdition",
    book_format: "bookFormat",
    character: "character",
    citation: "citation",
    colorist: "colorist",
    comment: "comment",
    comment_count: "commentCount",
    conditions_of_access: "conditionsOfAccess",
    content_location: "contentLocation",
    content_rating: "contentRating",
    content_reference_time: "contentReferenceTime",
    contributor: "contributor",
    copyright_holder: "copyrightHolder",
    copyright_notice: "copyrightNotice",
    copyright_year: "copyrightYear",
    correction: "correction",
    country_of_origin: "countryOfOrigin",
    creative_work_status: "creativeWorkStatus",
    creator: "creator",
    credit_text: "creditText",
    date_created: "dateCreated",
    date_modified: "dateModified",
    date_published: "datePublished",
    depth: "depth",
    description: "description",
    digital_source_type: "digitalSourceType",
    disambiguating_description: "disambiguatingDescription",
    discussion_url: "discussionUrl",
    display_location: "displayLocation",
    edit_eidr: "editEIDR",
    editor: "editor",
    educational_alignment: "educationalAlignment",
    educational_level: "educationalLevel",
    educational_use: "educationalUse",
    encoding: "encoding",
    encoding_format: "encodingFormat",
    encodings: "encodings",
    example_of_work: "exampleOfWork",
    expires: "expires",
    file_format: "fileFormat",
    funder: "funder",
    funding: "funding",
    genre: "genre",
    has_part: "hasPart",
    headline: "headline",
    height: "height",
    identifier: "identifier",
    illustrator: "illustrator",
    image: "image",
    in_language: "inLanguage",
    inker: "inker",
    interaction_statistic: "interactionStatistic",
    interactivity_type: "interactivityType",
    interpreted_as_claim: "interpretedAsClaim",
    is_accessible_for_free: "isAccessibleForFree",
    is_based_on: "isBasedOn",
    is_based_on_url: "isBasedOnUrl",
    is_family_friendly: "isFamilyFriendly",
    is_part_of: "isPartOf",
    isbn: "isbn",
    keywords: "keywords",
    learning_resource_type: "learningResourceType",
    letterer: "letterer",
    license: "license",
    location_created: "locationCreated",
    main_entity: "mainEntity",
    main_entity_of_page: "mainEntityOfPage",
    maintainer: "maintainer",
    material: "material",
    material_extent: "materialExtent",
    mentions: "mentions",
    name: "name",
    number_of_pages: "numberOfPages",
    offers: "offers",
    owner: "owner",
    pattern: "pattern",
    penciler: "penciler",
    position: "position",
    potential_action: "potentialAction",
    producer: "producer",
    provider: "provider",
    publication: "publication",
    publisher: "publisher",
    publisher_imprint: "publisherImprint",
    publishing_principles: "publishingPrinciples",
    recorded_at: "recordedAt",
    released_event: "releasedEvent",
    review: "review",
    reviews: "reviews",
    same_as: "sameAs",
    schema_version: "schemaVersion",
    sd_date_published: "sdDatePublished",
    sd_license: "sdLicense",
    sd_publisher: "sdPublisher",
    size: "size",
    source_organization: "sourceOrganization",
    spatial: "spatial",
    spatial_coverage: "spatialCoverage",
    sponsor: "sponsor",
    subject_of: "subjectOf",
    surface: "surface",
    teaches: "teaches",
    temporal: "temporal",
    temporal_coverage: "temporalCoverage",
    text: "text",
    thumbnail: "thumbnail",
    thumbnail_url: "thumbnailUrl",
    time_required: "timeRequired",
    translation_of_work: "translationOfWork",
    translator: "translator",
    typical_age_range: "typicalAgeRange",
    url: "url",
    usage_info: "usageInfo",
    version: "version",
    video: "video",
    weight: "weight",
    width: "width",
    word_count: "wordCount",
    work_example: "workExample",
    work_translation: "workTranslation"
  }

  @doc false
  def __schema_org__, do: %{type: "SequentialArt", json_keys: @json_keys}

  @doc "Builds an empty `SchemaOrg.SequentialArt` struct."
  def new, do: %__MODULE__{}
end
