defmodule SchemaOrg.Service do
  @moduledoc "A service provided by an organization, e.g. delivery service, print services, etc."

  defstruct [
    :additional_type,
    :aggregate_rating,
    :alternate_name,
    :area_served,
    :audience,
    :available_channel,
    :award,
    :brand,
    :broker,
    :category,
    :description,
    :disambiguating_description,
    :has_certification,
    :has_offer_catalog,
    :hours_available,
    :identifier,
    :image,
    :is_related_to,
    :is_similar_to,
    :logo,
    :main_entity_of_page,
    :name,
    :offers,
    :owner,
    :potential_action,
    :produces,
    :provider,
    :provider_mobility,
    :review,
    :same_as,
    :service_area,
    :service_audience,
    :service_output,
    :service_type,
    :slogan,
    :subject_of,
    :terms_of_service,
    :url
  ]

  @json_keys %{
    additional_type: "additionalType",
    aggregate_rating: "aggregateRating",
    alternate_name: "alternateName",
    area_served: "areaServed",
    audience: "audience",
    available_channel: "availableChannel",
    award: "award",
    brand: "brand",
    broker: "broker",
    category: "category",
    description: "description",
    disambiguating_description: "disambiguatingDescription",
    has_certification: "hasCertification",
    has_offer_catalog: "hasOfferCatalog",
    hours_available: "hoursAvailable",
    identifier: "identifier",
    image: "image",
    is_related_to: "isRelatedTo",
    is_similar_to: "isSimilarTo",
    logo: "logo",
    main_entity_of_page: "mainEntityOfPage",
    name: "name",
    offers: "offers",
    owner: "owner",
    potential_action: "potentialAction",
    produces: "produces",
    provider: "provider",
    provider_mobility: "providerMobility",
    review: "review",
    same_as: "sameAs",
    service_area: "serviceArea",
    service_audience: "serviceAudience",
    service_output: "serviceOutput",
    service_type: "serviceType",
    slogan: "slogan",
    subject_of: "subjectOf",
    terms_of_service: "termsOfService",
    url: "url"
  }

  @doc false
  def __schema_org__, do: %{type: "Service", json_keys: @json_keys}

  @doc "Builds an empty `SchemaOrg.Service` struct."
  def new, do: %__MODULE__{}
end
