defmodule SchemaOrg.SpecialAnnouncement do
  @moduledoc "A SpecialAnnouncement combines a simple date-stamped textual information update\n      with contextualized Web links and other structured data.  It represents an information update made by a\n      locally-oriented organization, for example schools, pharmacies, healthcare providers,  community groups, police,\n      local government.\n\nFor work in progress guidelines on Coronavirus-related markup see [this doc](https://docs.google.com/document/d/14ikaGCKxo50rRM7nvKSlbUpjyIk2WMQd3IkB1lItlrM/edit#).\n\nThe motivating scenario for SpecialAnnouncement is the [Coronavirus pandemic](https://en.wikipedia.org/wiki/2019%E2%80%9320_coronavirus_pandemic), and the initial vocabulary is oriented to this urgent situation. Schema.org\nexpect to improve the markup iteratively as it is deployed and as feedback emerges from use. In addition to our\nusual [Github entry](https://github.com/schemaorg/schemaorg/issues/2490), feedback comments can also be provided in [this document](https://docs.google.com/document/d/1fpdFFxk8s87CWwACs53SGkYv3aafSxz_DTtOQxMrBJQ/edit#).\n\n\nWhile this schema is designed to communicate urgent crisis-related information, it is not the same as an emergency warning technology like [CAP](https://en.wikipedia.org/wiki/Common_Alerting_Protocol), although there may be overlaps. The intent is to cover\nthe kinds of everyday practical information being posted to existing websites during an emergency situation.\n\nSeveral kinds of information can be provided:\n\nWe encourage the provision of \"name\", \"text\", \"datePosted\", \"expires\" (if appropriate), \"category\" and\n\"url\" as a simple baseline. It is important to provide a value for \"category\" where possible, most ideally as a well known\nURL from Wikipedia or Wikidata. In the case of the 2019-2020 Coronavirus pandemic, this should be \"https://en.wikipedia.org/w/index.php?title=2019-20\\_coronavirus\\_pandemic\" or \"https://www.wikidata.org/wiki/Q81068910\".\n\nFor many of the possible properties, values can either be simple links or an inline description, depending on whether a summary is available. For a link, provide just the URL of the appropriate page as the property's value. For an inline description, use a [[WebContent]] type, and provide the url as a property of that, alongside at least a simple \"[[text]]\" summary of the page. It is\nunlikely that a single SpecialAnnouncement will need all of the possible properties simultaneously.\n\nWe expect that in many cases the page referenced might contain more specialized structured data, e.g. contact info, [[openingHours]], [[Event]], [[FAQPage]] etc. By linking to those pages from a [[SpecialAnnouncement]] you can help make it clearer that the events are related to the situation (e.g. Coronavirus) indicated by the [[category]] property of the [[SpecialAnnouncement]].\n\nMany [[SpecialAnnouncement]]s will relate to particular regions and to identifiable local organizations. Use [[spatialCoverage]] for the region, and [[announcementLocation]] to indicate specific [[LocalBusiness]]es and [[CivicStructure]]s. If the announcement affects both a particular region and a specific location (for example, a library closure that serves an entire region), use both [[spatialCoverage]] and [[announcementLocation]].\n\nThe [[about]] property can be used to indicate entities that are the focus of the announcement. We now recommend using [[about]] only\nfor representing non-location entities (e.g. a [[Course]] or a [[RadioStation]]). For places, use [[announcementLocation]] and [[spatialCoverage]]. Consumers of this markup should be aware that the initial design encouraged the use of [[about]] for locations too.\n\nThe basic content of [[SpecialAnnouncement]] is similar to that of an [RSS](https://en.wikipedia.org/wiki/RSS) or [Atom](https://en.wikipedia.org/wiki/Atom_(Web_standard)) feed. For publishers without such feeds, basic feed-like information can be shared by posting\n[[SpecialAnnouncement]] updates in a page, e.g. using JSON-LD. For sites with Atom/RSS functionality, you can point to a feed\nwith the [[webFeed]] property. This can be a simple URL, or an inline [[DataFeed]] object, with [[encodingFormat]] providing\nmedia type information, e.g. \"application/rss+xml\" or \"application/atom+xml\".\n"

  defstruct [
    :about,
    :abstract,
    :access_mode,
    :access_mode_sufficient,
    :accessibility_api,
    :accessibility_control,
    :accessibility_feature,
    :accessibility_hazard,
    :accessibility_summary,
    :accountable_person,
    :acquire_license_page,
    :additional_type,
    :aggregate_rating,
    :alternate_name,
    :alternative_headline,
    :announcement_location,
    :archived_at,
    :assesses,
    :associated_media,
    :audience,
    :audio,
    :author,
    :award,
    :awards,
    :category,
    :character,
    :citation,
    :comment,
    :comment_count,
    :conditions_of_access,
    :content_location,
    :content_rating,
    :content_reference_time,
    :contributor,
    :copyright_holder,
    :copyright_notice,
    :copyright_year,
    :correction,
    :country_of_origin,
    :creative_work_status,
    :creator,
    :credit_text,
    :date_created,
    :date_modified,
    :date_posted,
    :date_published,
    :description,
    :digital_source_type,
    :disambiguating_description,
    :discussion_url,
    :disease_prevention_info,
    :disease_spread_statistics,
    :display_location,
    :edit_eidr,
    :editor,
    :educational_alignment,
    :educational_level,
    :educational_use,
    :encoding,
    :encoding_format,
    :encodings,
    :example_of_work,
    :expires,
    :file_format,
    :funder,
    :funding,
    :genre,
    :getting_tested_info,
    :government_benefits_info,
    :has_part,
    :headline,
    :identifier,
    :image,
    :in_language,
    :interaction_statistic,
    :interactivity_type,
    :interpreted_as_claim,
    :is_accessible_for_free,
    :is_based_on,
    :is_based_on_url,
    :is_family_friendly,
    :is_part_of,
    :keywords,
    :learning_resource_type,
    :license,
    :location_created,
    :main_entity,
    :main_entity_of_page,
    :maintainer,
    :material,
    :material_extent,
    :mentions,
    :name,
    :news_updates_and_guidelines,
    :offers,
    :owner,
    :pattern,
    :position,
    :potential_action,
    :producer,
    :provider,
    :public_transport_closures_info,
    :publication,
    :publisher,
    :publisher_imprint,
    :publishing_principles,
    :quarantine_guidelines,
    :recorded_at,
    :released_event,
    :review,
    :reviews,
    :same_as,
    :schema_version,
    :school_closures_info,
    :sd_date_published,
    :sd_license,
    :sd_publisher,
    :size,
    :source_organization,
    :spatial,
    :spatial_coverage,
    :sponsor,
    :subject_of,
    :teaches,
    :temporal,
    :temporal_coverage,
    :text,
    :thumbnail,
    :thumbnail_url,
    :time_required,
    :translation_of_work,
    :translator,
    :travel_bans,
    :typical_age_range,
    :url,
    :usage_info,
    :version,
    :video,
    :web_feed,
    :word_count,
    :work_example,
    :work_translation
  ]

  @json_keys %{
    about: "about",
    abstract: "abstract",
    access_mode: "accessMode",
    access_mode_sufficient: "accessModeSufficient",
    accessibility_api: "accessibilityAPI",
    accessibility_control: "accessibilityControl",
    accessibility_feature: "accessibilityFeature",
    accessibility_hazard: "accessibilityHazard",
    accessibility_summary: "accessibilitySummary",
    accountable_person: "accountablePerson",
    acquire_license_page: "acquireLicensePage",
    additional_type: "additionalType",
    aggregate_rating: "aggregateRating",
    alternate_name: "alternateName",
    alternative_headline: "alternativeHeadline",
    announcement_location: "announcementLocation",
    archived_at: "archivedAt",
    assesses: "assesses",
    associated_media: "associatedMedia",
    audience: "audience",
    audio: "audio",
    author: "author",
    award: "award",
    awards: "awards",
    category: "category",
    character: "character",
    citation: "citation",
    comment: "comment",
    comment_count: "commentCount",
    conditions_of_access: "conditionsOfAccess",
    content_location: "contentLocation",
    content_rating: "contentRating",
    content_reference_time: "contentReferenceTime",
    contributor: "contributor",
    copyright_holder: "copyrightHolder",
    copyright_notice: "copyrightNotice",
    copyright_year: "copyrightYear",
    correction: "correction",
    country_of_origin: "countryOfOrigin",
    creative_work_status: "creativeWorkStatus",
    creator: "creator",
    credit_text: "creditText",
    date_created: "dateCreated",
    date_modified: "dateModified",
    date_posted: "datePosted",
    date_published: "datePublished",
    description: "description",
    digital_source_type: "digitalSourceType",
    disambiguating_description: "disambiguatingDescription",
    discussion_url: "discussionUrl",
    disease_prevention_info: "diseasePreventionInfo",
    disease_spread_statistics: "diseaseSpreadStatistics",
    display_location: "displayLocation",
    edit_eidr: "editEIDR",
    editor: "editor",
    educational_alignment: "educationalAlignment",
    educational_level: "educationalLevel",
    educational_use: "educationalUse",
    encoding: "encoding",
    encoding_format: "encodingFormat",
    encodings: "encodings",
    example_of_work: "exampleOfWork",
    expires: "expires",
    file_format: "fileFormat",
    funder: "funder",
    funding: "funding",
    genre: "genre",
    getting_tested_info: "gettingTestedInfo",
    government_benefits_info: "governmentBenefitsInfo",
    has_part: "hasPart",
    headline: "headline",
    identifier: "identifier",
    image: "image",
    in_language: "inLanguage",
    interaction_statistic: "interactionStatistic",
    interactivity_type: "interactivityType",
    interpreted_as_claim: "interpretedAsClaim",
    is_accessible_for_free: "isAccessibleForFree",
    is_based_on: "isBasedOn",
    is_based_on_url: "isBasedOnUrl",
    is_family_friendly: "isFamilyFriendly",
    is_part_of: "isPartOf",
    keywords: "keywords",
    learning_resource_type: "learningResourceType",
    license: "license",
    location_created: "locationCreated",
    main_entity: "mainEntity",
    main_entity_of_page: "mainEntityOfPage",
    maintainer: "maintainer",
    material: "material",
    material_extent: "materialExtent",
    mentions: "mentions",
    name: "name",
    news_updates_and_guidelines: "newsUpdatesAndGuidelines",
    offers: "offers",
    owner: "owner",
    pattern: "pattern",
    position: "position",
    potential_action: "potentialAction",
    producer: "producer",
    provider: "provider",
    public_transport_closures_info: "publicTransportClosuresInfo",
    publication: "publication",
    publisher: "publisher",
    publisher_imprint: "publisherImprint",
    publishing_principles: "publishingPrinciples",
    quarantine_guidelines: "quarantineGuidelines",
    recorded_at: "recordedAt",
    released_event: "releasedEvent",
    review: "review",
    reviews: "reviews",
    same_as: "sameAs",
    schema_version: "schemaVersion",
    school_closures_info: "schoolClosuresInfo",
    sd_date_published: "sdDatePublished",
    sd_license: "sdLicense",
    sd_publisher: "sdPublisher",
    size: "size",
    source_organization: "sourceOrganization",
    spatial: "spatial",
    spatial_coverage: "spatialCoverage",
    sponsor: "sponsor",
    subject_of: "subjectOf",
    teaches: "teaches",
    temporal: "temporal",
    temporal_coverage: "temporalCoverage",
    text: "text",
    thumbnail: "thumbnail",
    thumbnail_url: "thumbnailUrl",
    time_required: "timeRequired",
    translation_of_work: "translationOfWork",
    translator: "translator",
    travel_bans: "travelBans",
    typical_age_range: "typicalAgeRange",
    url: "url",
    usage_info: "usageInfo",
    version: "version",
    video: "video",
    web_feed: "webFeed",
    word_count: "wordCount",
    work_example: "workExample",
    work_translation: "workTranslation"
  }

  @doc false
  def __schema_org__, do: %{type: "SpecialAnnouncement", json_keys: @json_keys}

  @doc "Builds an empty `SchemaOrg.SpecialAnnouncement` struct."
  def new, do: %__MODULE__{}
end
