defmodule SchemaOrg.VitalSign do
  @moduledoc "Vital signs are measures of various physiological functions in order to assess the most basic body functions."

  defstruct [
    :additional_type,
    :alternate_name,
    :associated_anatomy,
    :cause,
    :code,
    :description,
    :differential_diagnosis,
    :disambiguating_description,
    :drug,
    :epidemiology,
    :expected_prognosis,
    :funding,
    :guideline,
    :identifier,
    :identifying_exam,
    :identifying_test,
    :image,
    :legal_status,
    :main_entity_of_page,
    :medicine_system,
    :name,
    :natural_progression,
    :owner,
    :pathophysiology,
    :possible_complication,
    :possible_treatment,
    :potential_action,
    :primary_prevention,
    :recognizing_authority,
    :relevant_specialty,
    :risk_factor,
    :same_as,
    :secondary_prevention,
    :sign_or_symptom,
    :stage,
    :status,
    :study,
    :subject_of,
    :typical_test,
    :url
  ]

  @json_keys %{
    additional_type: "additionalType",
    alternate_name: "alternateName",
    associated_anatomy: "associatedAnatomy",
    cause: "cause",
    code: "code",
    description: "description",
    differential_diagnosis: "differentialDiagnosis",
    disambiguating_description: "disambiguatingDescription",
    drug: "drug",
    epidemiology: "epidemiology",
    expected_prognosis: "expectedPrognosis",
    funding: "funding",
    guideline: "guideline",
    identifier: "identifier",
    identifying_exam: "identifyingExam",
    identifying_test: "identifyingTest",
    image: "image",
    legal_status: "legalStatus",
    main_entity_of_page: "mainEntityOfPage",
    medicine_system: "medicineSystem",
    name: "name",
    natural_progression: "naturalProgression",
    owner: "owner",
    pathophysiology: "pathophysiology",
    possible_complication: "possibleComplication",
    possible_treatment: "possibleTreatment",
    potential_action: "potentialAction",
    primary_prevention: "primaryPrevention",
    recognizing_authority: "recognizingAuthority",
    relevant_specialty: "relevantSpecialty",
    risk_factor: "riskFactor",
    same_as: "sameAs",
    secondary_prevention: "secondaryPrevention",
    sign_or_symptom: "signOrSymptom",
    stage: "stage",
    status: "status",
    study: "study",
    subject_of: "subjectOf",
    typical_test: "typicalTest",
    url: "url"
  }

  @doc false
  def __schema_org__, do: %{type: "VitalSign", json_keys: @json_keys}

  @doc "Builds an empty `SchemaOrg.VitalSign` struct."
  def new, do: %__MODULE__{}
end
